/*
 * JSP generated by Resin Professional 3.1.3 (built Sun, 07 Oct 2007 06:30:19 PDT)
 */

package _jsp._web_22dinf._jsp._base._system._manager;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _manager_0index__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = com.caucho.jsp.QJspFactory.allocatePageContext(this, _jsp_application, request, response, null, null, 8192, true, false);
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html; charset=UTF-8");
    request.setCharacterEncoding("UTF-8");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      com.caucho.jsp.QJspFactory.freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != -5493130486421572921L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    long lastModified = 0;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      Object oDepend = _caucho_depends.get(i);
      if (oDepend instanceof com.caucho.vfs.Depend) {
        com.caucho.vfs.Depend depend = (com.caucho.vfs.Depend) oDepend;
        if (lastModified < depend.getLastModified())
          lastModified = depend.getLastModified();
      }
    }

    return lastModified;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/jsp/base/system/manager/manager_index.jsp"), 5341589968071823547L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  private final static char []_jsp_string0;
  static {
    _jsp_string0 = "\r\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html;charset=UTF-8\"/>\r\n<title>\u7ba1\u7406\u4e2d\u5fc3 - AIJIACMS\u623f\u4ea7\u7f51\u7ad9 - Powered By AIJIACMS   \u5546\u4e1a\u7248 V7.28 R20161111 UTF-8 ZH-CN</title>\r\n<meta name=\"robots\" content=\"noindex,nofollow\"/>\r\n<meta name=\"generator\" content=\"AIJIACMS   - www.aijiacms.com\"/>\r\n<meta http-equiv=\"x-ua-compatible\" content=\"IE=8\"/>\r\n<link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"http://t8.yuandongguanggao.com/favicon.ico\"/>\r\n<link rel=\"bookmark\" type=\"image/x-icon\" href=\"http://t8.yuandongguanggao.com/favicon.ico\"/>\r\n</head>\r\n<noscript><br/><br/><br/><center><h1>\u60a8\u7684\u6d4f\u89c8\u5668\u4e0d\u652f\u6301JAVASCRIPT,\u8bf7\u66f4\u6362\u652f\u6301JAVASCRIPT\u7684\u6d4f\u89c8\u5668</h1></center></noscript>\r\n<noframes><br/><br/><br/><center><h1>\u60a8\u7684\u6d4f\u89c8\u5668\u4e0d\u652f\u6301\u6846\u67b6,\u8bf7\u66f4\u6362\u652f\u6301\u6846\u67b6\u7684\u6d4f\u89c8\u5668</h1></center></noframes>\r\n<script type=\"text/javascript\" src=\"http://t8.yuandongguanggao.com/file/script/config.js\"></script>\r\n<frameset rows=\"96,*,4\"  frameborder=\"no\" border=\"0\" framespacing=\"0\" name=\"fra\"> \r\n<frame src=\"/base/system/manager_top.do\" noresize=\"noresize\" id=\"topFrame\" frameborder=\"0\" \r\nname=\"topFrame\" marginwidth=\"0\" marginheight=\"0\" scrolling=\"no\">\r\n	<frameset rows=\"*\" cols=\"185,*\" id=\"frame\" framespacing=\"0\" frameborder=\"no\" border=\"0\">\r\n		<frame name=\"left\" noresize scrolling=\"yes\" src=\"/base/system/manager_left.do\">\r\n		<frame name=\"main\" noresize scrolling=\"yes\" src=\"/base/system/manager_right.do\">\r\n	</frameset>\r\n</frameset>\r\n</html>".toCharArray();
  }
}
