package com.kuheng.entity.member;

import java.io.Serializable;
import java.util.Date;

public class EInfo  implements Serializable{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_info.id
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_info.msg_type
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    private Integer msgType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_info.msg_startprovince
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    private String msgStartprovince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_info.msg_startcity
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    private String msgStartcity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_info.msg_starttown
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    private String msgStarttown;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_info.msg_startaddr
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    private String msgStartaddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_info.msg_stopprovince
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    private String msgStopprovince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_info.msg_stopcity
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    private String msgStopcity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_info.msg_stoptown
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    private String msgStoptown;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_info.msg_stopaddr
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    private String msgStopaddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_info.msg_carlength
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    private String msgCarlength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_info.msg_cartype
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    private String msgCartype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_info.msg_goods
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    private String msgGoods;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_info.msg_goodsweight
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    private String msgGoodsweight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_info.msg_goodsunit
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    private String msgGoodsunit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_info.msg_js
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    private String msgJs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_info.msg_jsunit
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    private String msgJsunit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_info.msg_money
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    private String msgMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_info.msg_fusign
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    private Integer msgFusign;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_info.msg_remark
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    private String msgRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_info.msg_hiddencity
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    private String msgHiddencity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_info.msg_direct
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    private String msgDirect;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_info.msg_userid
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    private Integer msgUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_info.msg_cprovince
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    private String msgCprovince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_info.msg_code
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    private String msgCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_info.msg_ctown
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    private String msgCtown;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_info.msg_content
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    private String msgContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_info.msg_tel
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    private String msgTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_info.msg_userregdate
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    private String msgUserregdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_info.msg_useraddinfocounts
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    private String msgUseraddinfocounts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_info.msg_company
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    private String msgCompany;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_info.msg_name1
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    private String msgName1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_info.msg_name2
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    private String msgName2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_info.msg_tel1
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    private String msgTel1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_info.msg_tel2
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    private String msgTel2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_info.msg_couriernum
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    private String msgCouriernum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_info.msg_headimage
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    private String msgHeadimage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_info.msg_looknum
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    private Integer msgLooknum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_info.msg_sign
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    private Integer msgSign;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_info.msg_infosign
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    private Integer msgInfosign;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_info.msg_againNum
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    private Integer msgAgainnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_info.msg_ContentCode
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    private String msgContentcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_info.msg_addtime
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    private Date msgAddtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_info.local_province
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    private String localProvince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_info.local_city
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    private String localCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_info.local_town
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    private String localTown;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_info.local_addr
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    private String localAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_info.local_latitude
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    private String localLatitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_info.local_lontitude
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    private String localLontitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_info.local_ip
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    private String localIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_info.local_times
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    private Date localTimes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_info.id
     *
     * @return the value of e_info.id
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_info.id
     *
     * @param id the value for e_info.id
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_info.msg_type
     *
     * @return the value of e_info.msg_type
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public Integer getMsgType() {
        return msgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_info.msg_type
     *
     * @param msgType the value for e_info.msg_type
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public void setMsgType(Integer msgType) {
        this.msgType = msgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_info.msg_startprovince
     *
     * @return the value of e_info.msg_startprovince
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public String getMsgStartprovince() {
        return msgStartprovince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_info.msg_startprovince
     *
     * @param msgStartprovince the value for e_info.msg_startprovince
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public void setMsgStartprovince(String msgStartprovince) {
        this.msgStartprovince = msgStartprovince == null ? null : msgStartprovince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_info.msg_startcity
     *
     * @return the value of e_info.msg_startcity
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public String getMsgStartcity() {
        return msgStartcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_info.msg_startcity
     *
     * @param msgStartcity the value for e_info.msg_startcity
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public void setMsgStartcity(String msgStartcity) {
        this.msgStartcity = msgStartcity == null ? null : msgStartcity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_info.msg_starttown
     *
     * @return the value of e_info.msg_starttown
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public String getMsgStarttown() {
        return msgStarttown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_info.msg_starttown
     *
     * @param msgStarttown the value for e_info.msg_starttown
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public void setMsgStarttown(String msgStarttown) {
        this.msgStarttown = msgStarttown == null ? null : msgStarttown.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_info.msg_startaddr
     *
     * @return the value of e_info.msg_startaddr
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public String getMsgStartaddr() {
        return msgStartaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_info.msg_startaddr
     *
     * @param msgStartaddr the value for e_info.msg_startaddr
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public void setMsgStartaddr(String msgStartaddr) {
        this.msgStartaddr = msgStartaddr == null ? null : msgStartaddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_info.msg_stopprovince
     *
     * @return the value of e_info.msg_stopprovince
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public String getMsgStopprovince() {
        return msgStopprovince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_info.msg_stopprovince
     *
     * @param msgStopprovince the value for e_info.msg_stopprovince
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public void setMsgStopprovince(String msgStopprovince) {
        this.msgStopprovince = msgStopprovince == null ? null : msgStopprovince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_info.msg_stopcity
     *
     * @return the value of e_info.msg_stopcity
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public String getMsgStopcity() {
        return msgStopcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_info.msg_stopcity
     *
     * @param msgStopcity the value for e_info.msg_stopcity
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public void setMsgStopcity(String msgStopcity) {
        this.msgStopcity = msgStopcity == null ? null : msgStopcity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_info.msg_stoptown
     *
     * @return the value of e_info.msg_stoptown
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public String getMsgStoptown() {
        return msgStoptown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_info.msg_stoptown
     *
     * @param msgStoptown the value for e_info.msg_stoptown
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public void setMsgStoptown(String msgStoptown) {
        this.msgStoptown = msgStoptown == null ? null : msgStoptown.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_info.msg_stopaddr
     *
     * @return the value of e_info.msg_stopaddr
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public String getMsgStopaddr() {
        return msgStopaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_info.msg_stopaddr
     *
     * @param msgStopaddr the value for e_info.msg_stopaddr
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public void setMsgStopaddr(String msgStopaddr) {
        this.msgStopaddr = msgStopaddr == null ? null : msgStopaddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_info.msg_carlength
     *
     * @return the value of e_info.msg_carlength
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public String getMsgCarlength() {
        return msgCarlength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_info.msg_carlength
     *
     * @param msgCarlength the value for e_info.msg_carlength
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public void setMsgCarlength(String msgCarlength) {
        this.msgCarlength = msgCarlength == null ? null : msgCarlength.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_info.msg_cartype
     *
     * @return the value of e_info.msg_cartype
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public String getMsgCartype() {
        return msgCartype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_info.msg_cartype
     *
     * @param msgCartype the value for e_info.msg_cartype
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public void setMsgCartype(String msgCartype) {
        this.msgCartype = msgCartype == null ? null : msgCartype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_info.msg_goods
     *
     * @return the value of e_info.msg_goods
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public String getMsgGoods() {
        return msgGoods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_info.msg_goods
     *
     * @param msgGoods the value for e_info.msg_goods
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public void setMsgGoods(String msgGoods) {
        this.msgGoods = msgGoods == null ? null : msgGoods.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_info.msg_goodsweight
     *
     * @return the value of e_info.msg_goodsweight
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public String getMsgGoodsweight() {
        return msgGoodsweight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_info.msg_goodsweight
     *
     * @param msgGoodsweight the value for e_info.msg_goodsweight
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public void setMsgGoodsweight(String msgGoodsweight) {
        this.msgGoodsweight = msgGoodsweight == null ? null : msgGoodsweight.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_info.msg_goodsunit
     *
     * @return the value of e_info.msg_goodsunit
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public String getMsgGoodsunit() {
        return msgGoodsunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_info.msg_goodsunit
     *
     * @param msgGoodsunit the value for e_info.msg_goodsunit
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public void setMsgGoodsunit(String msgGoodsunit) {
        this.msgGoodsunit = msgGoodsunit == null ? null : msgGoodsunit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_info.msg_js
     *
     * @return the value of e_info.msg_js
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public String getMsgJs() {
        return msgJs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_info.msg_js
     *
     * @param msgJs the value for e_info.msg_js
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public void setMsgJs(String msgJs) {
        this.msgJs = msgJs == null ? null : msgJs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_info.msg_jsunit
     *
     * @return the value of e_info.msg_jsunit
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public String getMsgJsunit() {
        return msgJsunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_info.msg_jsunit
     *
     * @param msgJsunit the value for e_info.msg_jsunit
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public void setMsgJsunit(String msgJsunit) {
        this.msgJsunit = msgJsunit == null ? null : msgJsunit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_info.msg_money
     *
     * @return the value of e_info.msg_money
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public String getMsgMoney() {
        return msgMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_info.msg_money
     *
     * @param msgMoney the value for e_info.msg_money
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public void setMsgMoney(String msgMoney) {
        this.msgMoney = msgMoney == null ? null : msgMoney.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_info.msg_fusign
     *
     * @return the value of e_info.msg_fusign
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public Integer getMsgFusign() {
        return msgFusign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_info.msg_fusign
     *
     * @param msgFusign the value for e_info.msg_fusign
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public void setMsgFusign(Integer msgFusign) {
        this.msgFusign = msgFusign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_info.msg_remark
     *
     * @return the value of e_info.msg_remark
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public String getMsgRemark() {
        return msgRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_info.msg_remark
     *
     * @param msgRemark the value for e_info.msg_remark
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public void setMsgRemark(String msgRemark) {
        this.msgRemark = msgRemark == null ? null : msgRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_info.msg_hiddencity
     *
     * @return the value of e_info.msg_hiddencity
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public String getMsgHiddencity() {
        return msgHiddencity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_info.msg_hiddencity
     *
     * @param msgHiddencity the value for e_info.msg_hiddencity
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public void setMsgHiddencity(String msgHiddencity) {
        this.msgHiddencity = msgHiddencity == null ? null : msgHiddencity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_info.msg_direct
     *
     * @return the value of e_info.msg_direct
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public String getMsgDirect() {
        return msgDirect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_info.msg_direct
     *
     * @param msgDirect the value for e_info.msg_direct
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public void setMsgDirect(String msgDirect) {
        this.msgDirect = msgDirect == null ? null : msgDirect.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_info.msg_userid
     *
     * @return the value of e_info.msg_userid
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public Integer getMsgUserid() {
        return msgUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_info.msg_userid
     *
     * @param msgUserid the value for e_info.msg_userid
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public void setMsgUserid(Integer msgUserid) {
        this.msgUserid = msgUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_info.msg_cprovince
     *
     * @return the value of e_info.msg_cprovince
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public String getMsgCprovince() {
        return msgCprovince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_info.msg_cprovince
     *
     * @param msgCprovince the value for e_info.msg_cprovince
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public void setMsgCprovince(String msgCprovince) {
        this.msgCprovince = msgCprovince == null ? null : msgCprovince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_info.msg_code
     *
     * @return the value of e_info.msg_code
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public String getMsgCode() {
        return msgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_info.msg_code
     *
     * @param msgCode the value for e_info.msg_code
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public void setMsgCode(String msgCode) {
        this.msgCode = msgCode == null ? null : msgCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_info.msg_ctown
     *
     * @return the value of e_info.msg_ctown
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public String getMsgCtown() {
        return msgCtown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_info.msg_ctown
     *
     * @param msgCtown the value for e_info.msg_ctown
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public void setMsgCtown(String msgCtown) {
        this.msgCtown = msgCtown == null ? null : msgCtown.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_info.msg_content
     *
     * @return the value of e_info.msg_content
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public String getMsgContent() {
        return msgContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_info.msg_content
     *
     * @param msgContent the value for e_info.msg_content
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public void setMsgContent(String msgContent) {
        this.msgContent = msgContent == null ? null : msgContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_info.msg_tel
     *
     * @return the value of e_info.msg_tel
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public String getMsgTel() {
        return msgTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_info.msg_tel
     *
     * @param msgTel the value for e_info.msg_tel
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public void setMsgTel(String msgTel) {
        this.msgTel = msgTel == null ? null : msgTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_info.msg_userregdate
     *
     * @return the value of e_info.msg_userregdate
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public String getMsgUserregdate() {
        return msgUserregdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_info.msg_userregdate
     *
     * @param msgUserregdate the value for e_info.msg_userregdate
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public void setMsgUserregdate(String msgUserregdate) {
        this.msgUserregdate = msgUserregdate == null ? null : msgUserregdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_info.msg_useraddinfocounts
     *
     * @return the value of e_info.msg_useraddinfocounts
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public String getMsgUseraddinfocounts() {
        return msgUseraddinfocounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_info.msg_useraddinfocounts
     *
     * @param msgUseraddinfocounts the value for e_info.msg_useraddinfocounts
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public void setMsgUseraddinfocounts(String msgUseraddinfocounts) {
        this.msgUseraddinfocounts = msgUseraddinfocounts == null ? null : msgUseraddinfocounts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_info.msg_company
     *
     * @return the value of e_info.msg_company
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public String getMsgCompany() {
        return msgCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_info.msg_company
     *
     * @param msgCompany the value for e_info.msg_company
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public void setMsgCompany(String msgCompany) {
        this.msgCompany = msgCompany == null ? null : msgCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_info.msg_name1
     *
     * @return the value of e_info.msg_name1
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public String getMsgName1() {
        return msgName1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_info.msg_name1
     *
     * @param msgName1 the value for e_info.msg_name1
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public void setMsgName1(String msgName1) {
        this.msgName1 = msgName1 == null ? null : msgName1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_info.msg_name2
     *
     * @return the value of e_info.msg_name2
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public String getMsgName2() {
        return msgName2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_info.msg_name2
     *
     * @param msgName2 the value for e_info.msg_name2
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public void setMsgName2(String msgName2) {
        this.msgName2 = msgName2 == null ? null : msgName2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_info.msg_tel1
     *
     * @return the value of e_info.msg_tel1
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public String getMsgTel1() {
        return msgTel1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_info.msg_tel1
     *
     * @param msgTel1 the value for e_info.msg_tel1
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public void setMsgTel1(String msgTel1) {
        this.msgTel1 = msgTel1 == null ? null : msgTel1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_info.msg_tel2
     *
     * @return the value of e_info.msg_tel2
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public String getMsgTel2() {
        return msgTel2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_info.msg_tel2
     *
     * @param msgTel2 the value for e_info.msg_tel2
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public void setMsgTel2(String msgTel2) {
        this.msgTel2 = msgTel2 == null ? null : msgTel2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_info.msg_couriernum
     *
     * @return the value of e_info.msg_couriernum
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public String getMsgCouriernum() {
        return msgCouriernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_info.msg_couriernum
     *
     * @param msgCouriernum the value for e_info.msg_couriernum
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public void setMsgCouriernum(String msgCouriernum) {
        this.msgCouriernum = msgCouriernum == null ? null : msgCouriernum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_info.msg_headimage
     *
     * @return the value of e_info.msg_headimage
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public String getMsgHeadimage() {
        return msgHeadimage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_info.msg_headimage
     *
     * @param msgHeadimage the value for e_info.msg_headimage
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public void setMsgHeadimage(String msgHeadimage) {
        this.msgHeadimage = msgHeadimage == null ? null : msgHeadimage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_info.msg_looknum
     *
     * @return the value of e_info.msg_looknum
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public Integer getMsgLooknum() {
        return msgLooknum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_info.msg_looknum
     *
     * @param msgLooknum the value for e_info.msg_looknum
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public void setMsgLooknum(Integer msgLooknum) {
        this.msgLooknum = msgLooknum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_info.msg_sign
     *
     * @return the value of e_info.msg_sign
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public Integer getMsgSign() {
        return msgSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_info.msg_sign
     *
     * @param msgSign the value for e_info.msg_sign
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public void setMsgSign(Integer msgSign) {
        this.msgSign = msgSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_info.msg_infosign
     *
     * @return the value of e_info.msg_infosign
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public Integer getMsgInfosign() {
        return msgInfosign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_info.msg_infosign
     *
     * @param msgInfosign the value for e_info.msg_infosign
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public void setMsgInfosign(Integer msgInfosign) {
        this.msgInfosign = msgInfosign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_info.msg_againNum
     *
     * @return the value of e_info.msg_againNum
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public Integer getMsgAgainnum() {
        return msgAgainnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_info.msg_againNum
     *
     * @param msgAgainnum the value for e_info.msg_againNum
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public void setMsgAgainnum(Integer msgAgainnum) {
        this.msgAgainnum = msgAgainnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_info.msg_ContentCode
     *
     * @return the value of e_info.msg_ContentCode
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public String getMsgContentcode() {
        return msgContentcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_info.msg_ContentCode
     *
     * @param msgContentcode the value for e_info.msg_ContentCode
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public void setMsgContentcode(String msgContentcode) {
        this.msgContentcode = msgContentcode == null ? null : msgContentcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_info.msg_addtime
     *
     * @return the value of e_info.msg_addtime
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public Date getMsgAddtime() {
        return msgAddtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_info.msg_addtime
     *
     * @param msgAddtime the value for e_info.msg_addtime
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public void setMsgAddtime(Date msgAddtime) {
        this.msgAddtime = msgAddtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_info.local_province
     *
     * @return the value of e_info.local_province
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public String getLocalProvince() {
        return localProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_info.local_province
     *
     * @param localProvince the value for e_info.local_province
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public void setLocalProvince(String localProvince) {
        this.localProvince = localProvince == null ? null : localProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_info.local_city
     *
     * @return the value of e_info.local_city
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public String getLocalCity() {
        return localCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_info.local_city
     *
     * @param localCity the value for e_info.local_city
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public void setLocalCity(String localCity) {
        this.localCity = localCity == null ? null : localCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_info.local_town
     *
     * @return the value of e_info.local_town
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public String getLocalTown() {
        return localTown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_info.local_town
     *
     * @param localTown the value for e_info.local_town
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public void setLocalTown(String localTown) {
        this.localTown = localTown == null ? null : localTown.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_info.local_addr
     *
     * @return the value of e_info.local_addr
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public String getLocalAddr() {
        return localAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_info.local_addr
     *
     * @param localAddr the value for e_info.local_addr
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public void setLocalAddr(String localAddr) {
        this.localAddr = localAddr == null ? null : localAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_info.local_latitude
     *
     * @return the value of e_info.local_latitude
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public String getLocalLatitude() {
        return localLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_info.local_latitude
     *
     * @param localLatitude the value for e_info.local_latitude
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public void setLocalLatitude(String localLatitude) {
        this.localLatitude = localLatitude == null ? null : localLatitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_info.local_lontitude
     *
     * @return the value of e_info.local_lontitude
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public String getLocalLontitude() {
        return localLontitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_info.local_lontitude
     *
     * @param localLontitude the value for e_info.local_lontitude
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public void setLocalLontitude(String localLontitude) {
        this.localLontitude = localLontitude == null ? null : localLontitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_info.local_ip
     *
     * @return the value of e_info.local_ip
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public String getLocalIp() {
        return localIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_info.local_ip
     *
     * @param localIp the value for e_info.local_ip
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public void setLocalIp(String localIp) {
        this.localIp = localIp == null ? null : localIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_info.local_times
     *
     * @return the value of e_info.local_times
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public Date getLocalTimes() {
        return localTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_info.local_times
     *
     * @param localTimes the value for e_info.local_times
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    public void setLocalTimes(Date localTimes) {
        this.localTimes = localTimes;
    }
}