package com.kuheng.entity.member;

import java.io.Serializable;
import java.util.Date;

public class EUser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.id
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.username
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.password
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.memtype
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private Integer memtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.memtypesign
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private Integer memtypesign;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.pce
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private Integer pce;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.go_sign
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private Integer goSign;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.realsign
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private Integer realsign;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.loginsign
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private String loginsign;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.pcMac1
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private String pcmac1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.pcMac2
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private String pcmac2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.andMac1
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private String andmac1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.andMac2
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private String andmac2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.iosMac1
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private String iosmac1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.iosMac2
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private String iosmac2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.province
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.city
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.town
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private String town;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.address
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.line
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private String line;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.mobile
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.mobile2
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private String mobile2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.mobile3
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private String mobile3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.intel1
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private String intel1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.intel2
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private String intel2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.tel
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.company
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private String company;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.realname
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private String realname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.postcard
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private String postcard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.nicename
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private String nicename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.headimage
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private String headimage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.companyimage
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private String companyimage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.companyintro
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private String companyintro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.companypic
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private String companypic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.postcardimage1
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private String postcardimage1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.postcardimage2
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private String postcardimage2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.addCounts
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private Integer addcounts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.addCounts0
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private Integer addcounts0;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.addCounts1
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private Integer addcounts1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.addCounts2
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private Integer addcounts2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.loginCounts
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private Integer logincounts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.last_loginIP
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private String lastLoginip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.last_loginTimes
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private Date lastLogintimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.local_province
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private String localProvince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.local_city
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private String localCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.local_town
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private String localTown;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.local_addr
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private String localAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.local_latitude
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private String localLatitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.local_lontitude
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private String localLontitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.local_ip
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private String localIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.local_times
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private Date localTimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.adddate
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private Date adddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.enddate
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private Date enddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.addtime
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private Date addtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.handwrite
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private Integer handwrite;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.addfunc
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private Integer addfunc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.AddFuncDate
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private Date addfuncdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.HasAddTime
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private Integer hasaddtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.AddTimes
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private Integer addtimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.HasInfoNum
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private Integer hasinfonum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.InfoNum
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private Integer infonum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.InfoNum2
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private Integer infonum2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.AddInfoDate
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private Date addinfodate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.HasCharNum
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private Integer hascharnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.CharNum
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private Integer charnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.changeinfo
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private Integer changeinfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.changepwd
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private Integer changepwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.devices_reg
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private String devicesReg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_user.devices_login
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    private String devicesLogin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.id
     *
     * @return the value of e_user.id
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.id
     *
     * @param id the value for e_user.id
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.username
     *
     * @return the value of e_user.username
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.username
     *
     * @param username the value for e_user.username
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.password
     *
     * @return the value of e_user.password
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.password
     *
     * @param password the value for e_user.password
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.memtype
     *
     * @return the value of e_user.memtype
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public Integer getMemtype() {
        return memtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.memtype
     *
     * @param memtype the value for e_user.memtype
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setMemtype(Integer memtype) {
        this.memtype = memtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.memtypesign
     *
     * @return the value of e_user.memtypesign
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public Integer getMemtypesign() {
        return memtypesign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.memtypesign
     *
     * @param memtypesign the value for e_user.memtypesign
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setMemtypesign(Integer memtypesign) {
        this.memtypesign = memtypesign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.pce
     *
     * @return the value of e_user.pce
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public Integer getPce() {
        return pce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.pce
     *
     * @param pce the value for e_user.pce
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setPce(Integer pce) {
        this.pce = pce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.go_sign
     *
     * @return the value of e_user.go_sign
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public Integer getGoSign() {
        return goSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.go_sign
     *
     * @param goSign the value for e_user.go_sign
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setGoSign(Integer goSign) {
        this.goSign = goSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.realsign
     *
     * @return the value of e_user.realsign
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public Integer getRealsign() {
        return realsign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.realsign
     *
     * @param realsign the value for e_user.realsign
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setRealsign(Integer realsign) {
        this.realsign = realsign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.loginsign
     *
     * @return the value of e_user.loginsign
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public String getLoginsign() {
        return loginsign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.loginsign
     *
     * @param loginsign the value for e_user.loginsign
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setLoginsign(String loginsign) {
        this.loginsign = loginsign == null ? null : loginsign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.pcMac1
     *
     * @return the value of e_user.pcMac1
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public String getPcmac1() {
        return pcmac1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.pcMac1
     *
     * @param pcmac1 the value for e_user.pcMac1
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setPcmac1(String pcmac1) {
        this.pcmac1 = pcmac1 == null ? null : pcmac1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.pcMac2
     *
     * @return the value of e_user.pcMac2
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public String getPcmac2() {
        return pcmac2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.pcMac2
     *
     * @param pcmac2 the value for e_user.pcMac2
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setPcmac2(String pcmac2) {
        this.pcmac2 = pcmac2 == null ? null : pcmac2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.andMac1
     *
     * @return the value of e_user.andMac1
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public String getAndmac1() {
        return andmac1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.andMac1
     *
     * @param andmac1 the value for e_user.andMac1
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setAndmac1(String andmac1) {
        this.andmac1 = andmac1 == null ? null : andmac1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.andMac2
     *
     * @return the value of e_user.andMac2
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public String getAndmac2() {
        return andmac2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.andMac2
     *
     * @param andmac2 the value for e_user.andMac2
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setAndmac2(String andmac2) {
        this.andmac2 = andmac2 == null ? null : andmac2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.iosMac1
     *
     * @return the value of e_user.iosMac1
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public String getIosmac1() {
        return iosmac1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.iosMac1
     *
     * @param iosmac1 the value for e_user.iosMac1
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setIosmac1(String iosmac1) {
        this.iosmac1 = iosmac1 == null ? null : iosmac1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.iosMac2
     *
     * @return the value of e_user.iosMac2
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public String getIosmac2() {
        return iosmac2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.iosMac2
     *
     * @param iosmac2 the value for e_user.iosMac2
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setIosmac2(String iosmac2) {
        this.iosmac2 = iosmac2 == null ? null : iosmac2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.province
     *
     * @return the value of e_user.province
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.province
     *
     * @param province the value for e_user.province
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.city
     *
     * @return the value of e_user.city
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.city
     *
     * @param city the value for e_user.city
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.town
     *
     * @return the value of e_user.town
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public String getTown() {
        return town;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.town
     *
     * @param town the value for e_user.town
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setTown(String town) {
        this.town = town == null ? null : town.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.address
     *
     * @return the value of e_user.address
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.address
     *
     * @param address the value for e_user.address
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.line
     *
     * @return the value of e_user.line
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public String getLine() {
        return line;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.line
     *
     * @param line the value for e_user.line
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setLine(String line) {
        this.line = line == null ? null : line.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.mobile
     *
     * @return the value of e_user.mobile
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.mobile
     *
     * @param mobile the value for e_user.mobile
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.mobile2
     *
     * @return the value of e_user.mobile2
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public String getMobile2() {
        return mobile2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.mobile2
     *
     * @param mobile2 the value for e_user.mobile2
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setMobile2(String mobile2) {
        this.mobile2 = mobile2 == null ? null : mobile2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.mobile3
     *
     * @return the value of e_user.mobile3
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public String getMobile3() {
        return mobile3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.mobile3
     *
     * @param mobile3 the value for e_user.mobile3
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setMobile3(String mobile3) {
        this.mobile3 = mobile3 == null ? null : mobile3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.intel1
     *
     * @return the value of e_user.intel1
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public String getIntel1() {
        return intel1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.intel1
     *
     * @param intel1 the value for e_user.intel1
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setIntel1(String intel1) {
        this.intel1 = intel1 == null ? null : intel1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.intel2
     *
     * @return the value of e_user.intel2
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public String getIntel2() {
        return intel2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.intel2
     *
     * @param intel2 the value for e_user.intel2
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setIntel2(String intel2) {
        this.intel2 = intel2 == null ? null : intel2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.tel
     *
     * @return the value of e_user.tel
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.tel
     *
     * @param tel the value for e_user.tel
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.company
     *
     * @return the value of e_user.company
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.company
     *
     * @param company the value for e_user.company
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.realname
     *
     * @return the value of e_user.realname
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.realname
     *
     * @param realname the value for e_user.realname
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.postcard
     *
     * @return the value of e_user.postcard
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public String getPostcard() {
        return postcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.postcard
     *
     * @param postcard the value for e_user.postcard
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setPostcard(String postcard) {
        this.postcard = postcard == null ? null : postcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.nicename
     *
     * @return the value of e_user.nicename
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public String getNicename() {
        return nicename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.nicename
     *
     * @param nicename the value for e_user.nicename
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setNicename(String nicename) {
        this.nicename = nicename == null ? null : nicename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.headimage
     *
     * @return the value of e_user.headimage
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public String getHeadimage() {
        return headimage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.headimage
     *
     * @param headimage the value for e_user.headimage
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setHeadimage(String headimage) {
        this.headimage = headimage == null ? null : headimage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.companyimage
     *
     * @return the value of e_user.companyimage
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public String getCompanyimage() {
        return companyimage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.companyimage
     *
     * @param companyimage the value for e_user.companyimage
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setCompanyimage(String companyimage) {
        this.companyimage = companyimage == null ? null : companyimage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.companyintro
     *
     * @return the value of e_user.companyintro
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public String getCompanyintro() {
        return companyintro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.companyintro
     *
     * @param companyintro the value for e_user.companyintro
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setCompanyintro(String companyintro) {
        this.companyintro = companyintro == null ? null : companyintro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.companypic
     *
     * @return the value of e_user.companypic
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public String getCompanypic() {
        return companypic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.companypic
     *
     * @param companypic the value for e_user.companypic
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setCompanypic(String companypic) {
        this.companypic = companypic == null ? null : companypic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.postcardimage1
     *
     * @return the value of e_user.postcardimage1
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public String getPostcardimage1() {
        return postcardimage1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.postcardimage1
     *
     * @param postcardimage1 the value for e_user.postcardimage1
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setPostcardimage1(String postcardimage1) {
        this.postcardimage1 = postcardimage1 == null ? null : postcardimage1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.postcardimage2
     *
     * @return the value of e_user.postcardimage2
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public String getPostcardimage2() {
        return postcardimage2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.postcardimage2
     *
     * @param postcardimage2 the value for e_user.postcardimage2
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setPostcardimage2(String postcardimage2) {
        this.postcardimage2 = postcardimage2 == null ? null : postcardimage2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.addCounts
     *
     * @return the value of e_user.addCounts
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public Integer getAddcounts() {
        return addcounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.addCounts
     *
     * @param addcounts the value for e_user.addCounts
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setAddcounts(Integer addcounts) {
        this.addcounts = addcounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.addCounts0
     *
     * @return the value of e_user.addCounts0
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public Integer getAddcounts0() {
        return addcounts0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.addCounts0
     *
     * @param addcounts0 the value for e_user.addCounts0
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setAddcounts0(Integer addcounts0) {
        this.addcounts0 = addcounts0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.addCounts1
     *
     * @return the value of e_user.addCounts1
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public Integer getAddcounts1() {
        return addcounts1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.addCounts1
     *
     * @param addcounts1 the value for e_user.addCounts1
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setAddcounts1(Integer addcounts1) {
        this.addcounts1 = addcounts1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.addCounts2
     *
     * @return the value of e_user.addCounts2
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public Integer getAddcounts2() {
        return addcounts2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.addCounts2
     *
     * @param addcounts2 the value for e_user.addCounts2
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setAddcounts2(Integer addcounts2) {
        this.addcounts2 = addcounts2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.loginCounts
     *
     * @return the value of e_user.loginCounts
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public Integer getLogincounts() {
        return logincounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.loginCounts
     *
     * @param logincounts the value for e_user.loginCounts
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setLogincounts(Integer logincounts) {
        this.logincounts = logincounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.last_loginIP
     *
     * @return the value of e_user.last_loginIP
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public String getLastLoginip() {
        return lastLoginip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.last_loginIP
     *
     * @param lastLoginip the value for e_user.last_loginIP
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setLastLoginip(String lastLoginip) {
        this.lastLoginip = lastLoginip == null ? null : lastLoginip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.last_loginTimes
     *
     * @return the value of e_user.last_loginTimes
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public Date getLastLogintimes() {
        return lastLogintimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.last_loginTimes
     *
     * @param lastLogintimes the value for e_user.last_loginTimes
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setLastLogintimes(Date lastLogintimes) {
        this.lastLogintimes = lastLogintimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.local_province
     *
     * @return the value of e_user.local_province
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public String getLocalProvince() {
        return localProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.local_province
     *
     * @param localProvince the value for e_user.local_province
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setLocalProvince(String localProvince) {
        this.localProvince = localProvince == null ? null : localProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.local_city
     *
     * @return the value of e_user.local_city
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public String getLocalCity() {
        return localCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.local_city
     *
     * @param localCity the value for e_user.local_city
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setLocalCity(String localCity) {
        this.localCity = localCity == null ? null : localCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.local_town
     *
     * @return the value of e_user.local_town
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public String getLocalTown() {
        return localTown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.local_town
     *
     * @param localTown the value for e_user.local_town
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setLocalTown(String localTown) {
        this.localTown = localTown == null ? null : localTown.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.local_addr
     *
     * @return the value of e_user.local_addr
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public String getLocalAddr() {
        return localAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.local_addr
     *
     * @param localAddr the value for e_user.local_addr
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setLocalAddr(String localAddr) {
        this.localAddr = localAddr == null ? null : localAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.local_latitude
     *
     * @return the value of e_user.local_latitude
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public String getLocalLatitude() {
        return localLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.local_latitude
     *
     * @param localLatitude the value for e_user.local_latitude
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setLocalLatitude(String localLatitude) {
        this.localLatitude = localLatitude == null ? null : localLatitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.local_lontitude
     *
     * @return the value of e_user.local_lontitude
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public String getLocalLontitude() {
        return localLontitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.local_lontitude
     *
     * @param localLontitude the value for e_user.local_lontitude
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setLocalLontitude(String localLontitude) {
        this.localLontitude = localLontitude == null ? null : localLontitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.local_ip
     *
     * @return the value of e_user.local_ip
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public String getLocalIp() {
        return localIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.local_ip
     *
     * @param localIp the value for e_user.local_ip
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setLocalIp(String localIp) {
        this.localIp = localIp == null ? null : localIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.local_times
     *
     * @return the value of e_user.local_times
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public Date getLocalTimes() {
        return localTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.local_times
     *
     * @param localTimes the value for e_user.local_times
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setLocalTimes(Date localTimes) {
        this.localTimes = localTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.adddate
     *
     * @return the value of e_user.adddate
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public Date getAdddate() {
        return adddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.adddate
     *
     * @param adddate the value for e_user.adddate
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setAdddate(Date adddate) {
        this.adddate = adddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.enddate
     *
     * @return the value of e_user.enddate
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public Date getEnddate() {
        return enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.enddate
     *
     * @param enddate the value for e_user.enddate
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.addtime
     *
     * @return the value of e_user.addtime
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.addtime
     *
     * @param addtime the value for e_user.addtime
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.handwrite
     *
     * @return the value of e_user.handwrite
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public Integer getHandwrite() {
        return handwrite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.handwrite
     *
     * @param handwrite the value for e_user.handwrite
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setHandwrite(Integer handwrite) {
        this.handwrite = handwrite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.addfunc
     *
     * @return the value of e_user.addfunc
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public Integer getAddfunc() {
        return addfunc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.addfunc
     *
     * @param addfunc the value for e_user.addfunc
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setAddfunc(Integer addfunc) {
        this.addfunc = addfunc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.AddFuncDate
     *
     * @return the value of e_user.AddFuncDate
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public Date getAddfuncdate() {
        return addfuncdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.AddFuncDate
     *
     * @param addfuncdate the value for e_user.AddFuncDate
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setAddfuncdate(Date addfuncdate) {
        this.addfuncdate = addfuncdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.HasAddTime
     *
     * @return the value of e_user.HasAddTime
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public Integer getHasaddtime() {
        return hasaddtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.HasAddTime
     *
     * @param hasaddtime the value for e_user.HasAddTime
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setHasaddtime(Integer hasaddtime) {
        this.hasaddtime = hasaddtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.AddTimes
     *
     * @return the value of e_user.AddTimes
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public Integer getAddtimes() {
        return addtimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.AddTimes
     *
     * @param addtimes the value for e_user.AddTimes
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setAddtimes(Integer addtimes) {
        this.addtimes = addtimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.HasInfoNum
     *
     * @return the value of e_user.HasInfoNum
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public Integer getHasinfonum() {
        return hasinfonum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.HasInfoNum
     *
     * @param hasinfonum the value for e_user.HasInfoNum
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setHasinfonum(Integer hasinfonum) {
        this.hasinfonum = hasinfonum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.InfoNum
     *
     * @return the value of e_user.InfoNum
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public Integer getInfonum() {
        return infonum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.InfoNum
     *
     * @param infonum the value for e_user.InfoNum
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setInfonum(Integer infonum) {
        this.infonum = infonum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.InfoNum2
     *
     * @return the value of e_user.InfoNum2
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public Integer getInfonum2() {
        return infonum2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.InfoNum2
     *
     * @param infonum2 the value for e_user.InfoNum2
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setInfonum2(Integer infonum2) {
        this.infonum2 = infonum2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.AddInfoDate
     *
     * @return the value of e_user.AddInfoDate
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public Date getAddinfodate() {
        return addinfodate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.AddInfoDate
     *
     * @param addinfodate the value for e_user.AddInfoDate
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setAddinfodate(Date addinfodate) {
        this.addinfodate = addinfodate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.HasCharNum
     *
     * @return the value of e_user.HasCharNum
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public Integer getHascharnum() {
        return hascharnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.HasCharNum
     *
     * @param hascharnum the value for e_user.HasCharNum
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setHascharnum(Integer hascharnum) {
        this.hascharnum = hascharnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.CharNum
     *
     * @return the value of e_user.CharNum
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public Integer getCharnum() {
        return charnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.CharNum
     *
     * @param charnum the value for e_user.CharNum
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setCharnum(Integer charnum) {
        this.charnum = charnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.changeinfo
     *
     * @return the value of e_user.changeinfo
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public Integer getChangeinfo() {
        return changeinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.changeinfo
     *
     * @param changeinfo the value for e_user.changeinfo
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setChangeinfo(Integer changeinfo) {
        this.changeinfo = changeinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.changepwd
     *
     * @return the value of e_user.changepwd
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public Integer getChangepwd() {
        return changepwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.changepwd
     *
     * @param changepwd the value for e_user.changepwd
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setChangepwd(Integer changepwd) {
        this.changepwd = changepwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.devices_reg
     *
     * @return the value of e_user.devices_reg
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public String getDevicesReg() {
        return devicesReg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.devices_reg
     *
     * @param devicesReg the value for e_user.devices_reg
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setDevicesReg(String devicesReg) {
        this.devicesReg = devicesReg == null ? null : devicesReg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_user.devices_login
     *
     * @return the value of e_user.devices_login
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public String getDevicesLogin() {
        return devicesLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_user.devices_login
     *
     * @param devicesLogin the value for e_user.devices_login
     *
     * @mbg.generated Tue Sep 12 16:41:38 CST 2017
     */
    public void setDevicesLogin(String devicesLogin) {
        this.devicesLogin = devicesLogin == null ? null : devicesLogin.trim();
    }

	@Override
	public String toString() {
		return "EUser [id=" + id + ", username=" + username + ", password="
				+ password + ", memtype=" + memtype + ", memtypesign="
				+ memtypesign + ", pce=" + pce + ", goSign=" + goSign
				+ ", realsign=" + realsign + ", loginsign=" + loginsign
				+ ", pcmac1=" + pcmac1 + ", pcmac2=" + pcmac2 + ", andmac1="
				+ andmac1 + ", andmac2=" + andmac2 + ", iosmac1=" + iosmac1
				+ ", iosmac2=" + iosmac2 + ", province=" + province + ", city="
				+ city + ", town=" + town + ", address=" + address + ", line="
				+ line + ", mobile=" + mobile + ", mobile2=" + mobile2
				+ ", mobile3=" + mobile3 + ", intel1=" + intel1 + ", intel2="
				+ intel2 + ", tel=" + tel + ", company=" + company
				+ ", realname=" + realname + ", postcard=" + postcard
				+ ", nicename=" + nicename + ", headimage=" + headimage
				+ ", companyimage=" + companyimage + ", companyintro="
				+ companyintro + ", companypic=" + companypic
				+ ", postcardimage1=" + postcardimage1 + ", postcardimage2="
				+ postcardimage2 + ", addcounts=" + addcounts + ", addcounts0="
				+ addcounts0 + ", addcounts1=" + addcounts1 + ", addcounts2="
				+ addcounts2 + ", logincounts=" + logincounts
				+ ", lastLoginip=" + lastLoginip + ", lastLogintimes="
				+ lastLogintimes + ", localProvince=" + localProvince
				+ ", localCity=" + localCity + ", localTown=" + localTown
				+ ", localAddr=" + localAddr + ", localLatitude="
				+ localLatitude + ", localLontitude=" + localLontitude
				+ ", localIp=" + localIp + ", localTimes=" + localTimes
				+ ", adddate=" + adddate + ", enddate=" + enddate
				+ ", addtime=" + addtime + ", handwrite=" + handwrite
				+ ", addfunc=" + addfunc + ", addfuncdate=" + addfuncdate
				+ ", hasaddtime=" + hasaddtime + ", addtimes=" + addtimes
				+ ", hasinfonum=" + hasinfonum + ", infonum=" + infonum
				+ ", infonum2=" + infonum2 + ", addinfodate=" + addinfodate
				+ ", hascharnum=" + hascharnum + ", charnum=" + charnum
				+ ", changeinfo=" + changeinfo + ", changepwd=" + changepwd
				+ ", devicesReg=" + devicesReg + ", devicesLogin="
				+ devicesLogin + "]";
	}
    
}