package com.kuheng.entity.member;

import java.io.Serializable;

public class KuAdminLoginlog implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_admin_loginlog.itemid
     *
     * @mbggenerated Sun May 21 11:09:53 CST 2017
     */
    private Integer itemid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_admin_loginlog.truename
     *
     * @mbggenerated Sun May 21 11:09:53 CST 2017
     */
    private String truename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_admin_loginlog.username
     *
     * @mbggenerated Sun May 21 11:09:53 CST 2017
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_admin_loginlog.userid
     *
     * @mbggenerated Sun May 21 11:09:53 CST 2017
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_admin_loginlog.ip
     *
     * @mbggenerated Sun May 21 11:09:53 CST 2017
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_admin_loginlog.addtime
     *
     * @mbggenerated Sun May 21 11:09:53 CST 2017
     */
    private Integer addtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_admin_loginlog.itemid
     *
     * @return the value of ku_admin_loginlog.itemid
     *
     * @mbggenerated Sun May 21 11:09:53 CST 2017
     */
    public Integer getItemid() {
        return itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_admin_loginlog.itemid
     *
     * @param itemid the value for ku_admin_loginlog.itemid
     *
     * @mbggenerated Sun May 21 11:09:53 CST 2017
     */
    public void setItemid(Integer itemid) {
        this.itemid = itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_admin_loginlog.truename
     *
     * @return the value of ku_admin_loginlog.truename
     *
     * @mbggenerated Sun May 21 11:09:53 CST 2017
     */
    public String getTruename() {
        return truename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_admin_loginlog.truename
     *
     * @param truename the value for ku_admin_loginlog.truename
     *
     * @mbggenerated Sun May 21 11:09:53 CST 2017
     */
    public void setTruename(String truename) {
        this.truename = truename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_admin_loginlog.username
     *
     * @return the value of ku_admin_loginlog.username
     *
     * @mbggenerated Sun May 21 11:09:53 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_admin_loginlog.username
     *
     * @param username the value for ku_admin_loginlog.username
     *
     * @mbggenerated Sun May 21 11:09:53 CST 2017
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_admin_loginlog.userid
     *
     * @return the value of ku_admin_loginlog.userid
     *
     * @mbggenerated Sun May 21 11:09:53 CST 2017
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_admin_loginlog.userid
     *
     * @param userid the value for ku_admin_loginlog.userid
     *
     * @mbggenerated Sun May 21 11:09:53 CST 2017
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_admin_loginlog.ip
     *
     * @return the value of ku_admin_loginlog.ip
     *
     * @mbggenerated Sun May 21 11:09:53 CST 2017
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_admin_loginlog.ip
     *
     * @param ip the value for ku_admin_loginlog.ip
     *
     * @mbggenerated Sun May 21 11:09:53 CST 2017
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_admin_loginlog.addtime
     *
     * @return the value of ku_admin_loginlog.addtime
     *
     * @mbggenerated Sun May 21 11:09:53 CST 2017
     */
    public Integer getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_admin_loginlog.addtime
     *
     * @param addtime the value for ku_admin_loginlog.addtime
     *
     * @mbggenerated Sun May 21 11:09:53 CST 2017
     */
    public void setAddtime(Integer addtime) {
        this.addtime = addtime;
    }
}