package com.kuheng.entity.member;

import java.io.Serializable;

public class KuBank implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_bank.itemid
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private Integer itemid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_bank.userid
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_bank.bankname
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private String bankname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_bank.bankNO
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private String bankno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_bank.bankmobile
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private String bankmobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_bank.status
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private Boolean status;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_bank.apptype
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private int apptype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_bank.itemid
     *
     * @return the value of ku_bank.itemid
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public Integer getItemid() {
        return itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_bank.itemid
     *
     * @param itemid the value for ku_bank.itemid
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setItemid(Integer itemid) {
        this.itemid = itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_bank.apptype
     *
     * @return the value of ku_bank.itemid
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public Integer getApptype() {
        return apptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_bank.apptype
     *
     * @param itemid the value for ku_bank.apptype
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setApptype(Integer apptype) {
        this.apptype = apptype;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_bank.userid
     *
     * @return the value of ku_bank.userid
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_bank.userid
     *
     * @param userid the value for ku_bank.userid
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_bank.bankname
     *
     * @return the value of ku_bank.bankname
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public String getBankname() {
        return bankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_bank.bankname
     *
     * @param bankname the value for ku_bank.bankname
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setBankname(String bankname) {
        this.bankname = bankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_bank.bankNO
     *
     * @return the value of ku_bank.bankNO
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public String getBankno() {
        return bankno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_bank.bankNO
     *
     * @param bankno the value for ku_bank.bankNO
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setBankno(String bankno) {
        this.bankno = bankno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_bank.bankmobile
     *
     * @return the value of ku_bank.bankmobile
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public String getBankmobile() {
        return bankmobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_bank.bankmobile
     *
     * @param bankmobile the value for ku_bank.bankmobile
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setBankmobile(String bankmobile) {
        this.bankmobile = bankmobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_bank.status
     *
     * @return the value of ku_bank.status
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_bank.status
     *
     * @param status the value for ku_bank.status
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }
}