package com.kuheng.entity.member;

import java.io.Serializable;

public class KuCity implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_city.areaid
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private Integer areaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_city.areaname
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private String areaname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_city.pinyin
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private String pinyin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_city.parentid
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private Integer parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_city.arrparentid
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private String arrparentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_city.child
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private Boolean child;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_city.listorder
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private Short listorder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_city.level
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private Boolean level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_city.longitude
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private Double longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_city.latitude
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private Double latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_city.arrchildid
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private String arrchildid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_city.areaid
     *
     * @return the value of ku_city.areaid
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public Integer getAreaid() {
        return areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_city.areaid
     *
     * @param areaid the value for ku_city.areaid
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setAreaid(Integer areaid) {
        this.areaid = areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_city.areaname
     *
     * @return the value of ku_city.areaname
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public String getAreaname() {
        return areaname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_city.areaname
     *
     * @param areaname the value for ku_city.areaname
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setAreaname(String areaname) {
        this.areaname = areaname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_city.pinyin
     *
     * @return the value of ku_city.pinyin
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public String getPinyin() {
        return pinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_city.pinyin
     *
     * @param pinyin the value for ku_city.pinyin
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setPinyin(String pinyin) {
        this.pinyin = pinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_city.parentid
     *
     * @return the value of ku_city.parentid
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_city.parentid
     *
     * @param parentid the value for ku_city.parentid
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_city.arrparentid
     *
     * @return the value of ku_city.arrparentid
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public String getArrparentid() {
        return arrparentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_city.arrparentid
     *
     * @param arrparentid the value for ku_city.arrparentid
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setArrparentid(String arrparentid) {
        this.arrparentid = arrparentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_city.child
     *
     * @return the value of ku_city.child
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public Boolean getChild() {
        return child;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_city.child
     *
     * @param child the value for ku_city.child
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setChild(Boolean child) {
        this.child = child;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_city.listorder
     *
     * @return the value of ku_city.listorder
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public Short getListorder() {
        return listorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_city.listorder
     *
     * @param listorder the value for ku_city.listorder
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setListorder(Short listorder) {
        this.listorder = listorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_city.level
     *
     * @return the value of ku_city.level
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public Boolean getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_city.level
     *
     * @param level the value for ku_city.level
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setLevel(Boolean level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_city.longitude
     *
     * @return the value of ku_city.longitude
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_city.longitude
     *
     * @param longitude the value for ku_city.longitude
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_city.latitude
     *
     * @return the value of ku_city.latitude
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_city.latitude
     *
     * @param latitude the value for ku_city.latitude
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_city.arrchildid
     *
     * @return the value of ku_city.arrchildid
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public String getArrchildid() {
        return arrchildid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_city.arrchildid
     *
     * @param arrchildid the value for ku_city.arrchildid
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setArrchildid(String arrchildid) {
        this.arrchildid = arrchildid;
    }
}