package com.kuheng.entity.member;

import java.io.Serializable;

public class KuCompany implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_company.userid
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_company.company
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private String company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_company.applytype
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private Boolean applytype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_company.typeid
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private Integer typeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_company.catid
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private Integer catid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_company.business
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private String business;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_company.regyear
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private String regyear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_company.regmoney
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private String regmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_company.areaid
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private Integer areaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_company.address
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_company.companyphoto
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private String companyphoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_company.legal
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private String legal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_company.legalno
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private String legalno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_company.legalphoto1
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private String legalphoto1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_company.legalphoto2
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private String legalphoto2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_company.mainline
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private String mainline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_company.truename
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private String truename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_company.telephone
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_company.mobile
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_company.email
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_company.fax
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private String fax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_company.postcode
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private String postcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_company.qq
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_company.addtime
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private Integer addtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_company.edittime
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private Integer edittime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_company.validated
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private Boolean validated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_company.validtime
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private Integer validtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_company.status
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_company.ischeck
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private Integer ischeck;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_company.introduce
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private String introduce;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_company.userid
     *
     * @return the value of ku_company.userid
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_company.userid
     *
     * @param userid the value for ku_company.userid
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_company.company
     *
     * @return the value of ku_company.company
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_company.company
     *
     * @param company the value for ku_company.company
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setCompany(String company) {
        this.company = company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_company.applytype
     *
     * @return the value of ku_company.applytype
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public Boolean getApplytype() {
        return applytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_company.applytype
     *
     * @param applytype the value for ku_company.applytype
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setApplytype(Boolean applytype) {
        this.applytype = applytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_company.typeid
     *
     * @return the value of ku_company.typeid
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public Integer getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_company.typeid
     *
     * @param typeid the value for ku_company.typeid
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setTypeid(Integer typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_company.catid
     *
     * @return the value of ku_company.catid
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public Integer getCatid() {
        return catid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_company.catid
     *
     * @param catid the value for ku_company.catid
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setCatid(Integer catid) {
        this.catid = catid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_company.business
     *
     * @return the value of ku_company.business
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public String getBusiness() {
        return business;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_company.business
     *
     * @param business the value for ku_company.business
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setBusiness(String business) {
        this.business = business;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_company.regyear
     *
     * @return the value of ku_company.regyear
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public String getRegyear() {
        return regyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_company.regyear
     *
     * @param regyear the value for ku_company.regyear
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setRegyear(String regyear) {
        this.regyear = regyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_company.regmoney
     *
     * @return the value of ku_company.regmoney
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public String getRegmoney() {
        return regmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_company.regmoney
     *
     * @param regmoney the value for ku_company.regmoney
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setRegmoney(String regmoney) {
        this.regmoney = regmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_company.areaid
     *
     * @return the value of ku_company.areaid
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public Integer getAreaid() {
        return areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_company.areaid
     *
     * @param areaid the value for ku_company.areaid
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setAreaid(Integer areaid) {
        this.areaid = areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_company.address
     *
     * @return the value of ku_company.address
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_company.address
     *
     * @param address the value for ku_company.address
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_company.companyphoto
     *
     * @return the value of ku_company.companyphoto
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public String getCompanyphoto() {
        return companyphoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_company.companyphoto
     *
     * @param companyphoto the value for ku_company.companyphoto
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setCompanyphoto(String companyphoto) {
        this.companyphoto = companyphoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_company.legal
     *
     * @return the value of ku_company.legal
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public String getLegal() {
        return legal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_company.legal
     *
     * @param legal the value for ku_company.legal
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setLegal(String legal) {
        this.legal = legal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_company.legalno
     *
     * @return the value of ku_company.legalno
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public String getLegalno() {
        return legalno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_company.legalno
     *
     * @param legalno the value for ku_company.legalno
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setLegalno(String legalno) {
        this.legalno = legalno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_company.legalphoto1
     *
     * @return the value of ku_company.legalphoto1
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public String getLegalphoto1() {
        return legalphoto1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_company.legalphoto1
     *
     * @param legalphoto1 the value for ku_company.legalphoto1
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setLegalphoto1(String legalphoto1) {
        this.legalphoto1 = legalphoto1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_company.legalphoto2
     *
     * @return the value of ku_company.legalphoto2
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public String getLegalphoto2() {
        return legalphoto2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_company.legalphoto2
     *
     * @param legalphoto2 the value for ku_company.legalphoto2
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setLegalphoto2(String legalphoto2) {
        this.legalphoto2 = legalphoto2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_company.mainline
     *
     * @return the value of ku_company.mainline
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public String getMainline() {
        return mainline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_company.mainline
     *
     * @param mainline the value for ku_company.mainline
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setMainline(String mainline) {
        this.mainline = mainline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_company.truename
     *
     * @return the value of ku_company.truename
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public String getTruename() {
        return truename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_company.truename
     *
     * @param truename the value for ku_company.truename
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setTruename(String truename) {
        this.truename = truename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_company.telephone
     *
     * @return the value of ku_company.telephone
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_company.telephone
     *
     * @param telephone the value for ku_company.telephone
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_company.mobile
     *
     * @return the value of ku_company.mobile
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_company.mobile
     *
     * @param mobile the value for ku_company.mobile
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_company.email
     *
     * @return the value of ku_company.email
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_company.email
     *
     * @param email the value for ku_company.email
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_company.fax
     *
     * @return the value of ku_company.fax
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_company.fax
     *
     * @param fax the value for ku_company.fax
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setFax(String fax) {
        this.fax = fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_company.postcode
     *
     * @return the value of ku_company.postcode
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public String getPostcode() {
        return postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_company.postcode
     *
     * @param postcode the value for ku_company.postcode
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_company.qq
     *
     * @return the value of ku_company.qq
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_company.qq
     *
     * @param qq the value for ku_company.qq
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setQq(String qq) {
        this.qq = qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_company.addtime
     *
     * @return the value of ku_company.addtime
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public Integer getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_company.addtime
     *
     * @param addtime the value for ku_company.addtime
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setAddtime(Integer addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_company.edittime
     *
     * @return the value of ku_company.edittime
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public Integer getEdittime() {
        return edittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_company.edittime
     *
     * @param edittime the value for ku_company.edittime
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setEdittime(Integer edittime) {
        this.edittime = edittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_company.validated
     *
     * @return the value of ku_company.validated
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public Boolean getValidated() {
        return validated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_company.validated
     *
     * @param validated the value for ku_company.validated
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setValidated(Boolean validated) {
        this.validated = validated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_company.validtime
     *
     * @return the value of ku_company.validtime
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public Integer getValidtime() {
        return validtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_company.validtime
     *
     * @param validtime the value for ku_company.validtime
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setValidtime(Integer validtime) {
        this.validtime = validtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_company.status
     *
     * @return the value of ku_company.status
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_company.status
     *
     * @param status the value for ku_company.status
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_company.ischeck
     *
     * @return the value of ku_company.ischeck
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public Integer getIscheck() {
        return ischeck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_company.ischeck
     *
     * @param ischeck the value for ku_company.ischeck
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setIscheck(Integer ischeck) {
        this.ischeck = ischeck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_company.introduce
     *
     * @return the value of ku_company.introduce
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public String getIntroduce() {
        return introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_company.introduce
     *
     * @param introduce the value for ku_company.introduce
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setIntroduce(String introduce) {
        this.introduce = introduce;
    }
}