package com.kuheng.entity.member;

public class KuCollection {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_collection.itemid
     *
     * @mbg.generated Wed Nov 22 09:38:57 CST 2017
     */
    private Integer itemid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_collection.collectorid
     *
     * @mbg.generated Wed Nov 22 09:38:57 CST 2017
     */
    private Long collectorid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_collection.collectedid
     *
     * @mbg.generated Wed Nov 22 09:38:57 CST 2017
     */
    private Long collectedid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_collection.content
     *
     * @mbg.generated Wed Nov 22 09:38:57 CST 2017
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_collection.type
     *
     * @mbg.generated Wed Nov 22 09:38:57 CST 2017
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_collection.addtime
     *
     * @mbg.generated Wed Nov 22 09:38:57 CST 2017
     */
    private Integer addtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_collection.itemid
     *
     * @return the value of ku_collection.itemid
     *
     * @mbg.generated Wed Nov 22 09:38:57 CST 2017
     */
    public Integer getItemid() {
        return itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_collection.itemid
     *
     * @param itemid the value for ku_collection.itemid
     *
     * @mbg.generated Wed Nov 22 09:38:57 CST 2017
     */
    public void setItemid(Integer itemid) {
        this.itemid = itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_collection.collectorid
     *
     * @return the value of ku_collection.collectorid
     *
     * @mbg.generated Wed Nov 22 09:38:57 CST 2017
     */
    public Long getCollectorid() {
        return collectorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_collection.collectorid
     *
     * @param collectorid the value for ku_collection.collectorid
     *
     * @mbg.generated Wed Nov 22 09:38:57 CST 2017
     */
    public void setCollectorid(Long collectorid) {
        this.collectorid = collectorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_collection.collectedid
     *
     * @return the value of ku_collection.collectedid
     *
     * @mbg.generated Wed Nov 22 09:38:57 CST 2017
     */
    public Long getCollectedid() {
        return collectedid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_collection.collectedid
     *
     * @param collectedid the value for ku_collection.collectedid
     *
     * @mbg.generated Wed Nov 22 09:38:57 CST 2017
     */
    public void setCollectedid(Long collectedid) {
        this.collectedid = collectedid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_collection.content
     *
     * @return the value of ku_collection.content
     *
     * @mbg.generated Wed Nov 22 09:38:57 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_collection.content
     *
     * @param content the value for ku_collection.content
     *
     * @mbg.generated Wed Nov 22 09:38:57 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_collection.type
     *
     * @return the value of ku_collection.type
     *
     * @mbg.generated Wed Nov 22 09:38:57 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_collection.type
     *
     * @param type the value for ku_collection.type
     *
     * @mbg.generated Wed Nov 22 09:38:57 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_collection.addtime
     *
     * @return the value of ku_collection.addtime
     *
     * @mbg.generated Wed Nov 22 09:38:57 CST 2017
     */
    public Integer getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_collection.addtime
     *
     * @param addtime the value for ku_collection.addtime
     *
     * @mbg.generated Wed Nov 22 09:38:57 CST 2017
     */
    public void setAddtime(Integer addtime) {
        this.addtime = addtime;
    }
}