package com.kuheng.entity.member;

public class KuCredit {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_credit.itemid
     *
     * @mbg.generated Mon Dec 11 10:54:47 CST 2017
     */
    private Integer itemid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_credit.userid
     *
     * @mbg.generated Mon Dec 11 10:54:47 CST 2017
     */
    private Long userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_credit.value
     *
     * @mbg.generated Mon Dec 11 10:54:47 CST 2017
     */
    private Integer value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_credit.total
     *
     * @mbg.generated Mon Dec 11 10:54:47 CST 2017
     */
    private Integer total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_credit.reason
     *
     * @mbg.generated Mon Dec 11 10:54:47 CST 2017
     */
    private String reason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_credit.addtime
     *
     * @mbg.generated Mon Dec 11 10:54:47 CST 2017
     */
    private Integer addtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_credit.itemid
     *
     * @return the value of ku_credit.itemid
     *
     * @mbg.generated Mon Dec 11 10:54:47 CST 2017
     */
    public Integer getItemid() {
        return itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_credit.itemid
     *
     * @param itemid the value for ku_credit.itemid
     *
     * @mbg.generated Mon Dec 11 10:54:47 CST 2017
     */
    public void setItemid(Integer itemid) {
        this.itemid = itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_credit.userid
     *
     * @return the value of ku_credit.userid
     *
     * @mbg.generated Mon Dec 11 10:54:47 CST 2017
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_credit.userid
     *
     * @param userid the value for ku_credit.userid
     *
     * @mbg.generated Mon Dec 11 10:54:47 CST 2017
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_credit.value
     *
     * @return the value of ku_credit.value
     *
     * @mbg.generated Mon Dec 11 10:54:47 CST 2017
     */
    public Integer getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_credit.value
     *
     * @param value the value for ku_credit.value
     *
     * @mbg.generated Mon Dec 11 10:54:47 CST 2017
     */
    public void setValue(Integer value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_credit.total
     *
     * @return the value of ku_credit.total
     *
     * @mbg.generated Mon Dec 11 10:54:47 CST 2017
     */
    public Integer getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_credit.total
     *
     * @param total the value for ku_credit.total
     *
     * @mbg.generated Mon Dec 11 10:54:47 CST 2017
     */
    public void setTotal(Integer total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_credit.reason
     *
     * @return the value of ku_credit.reason
     *
     * @mbg.generated Mon Dec 11 10:54:47 CST 2017
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_credit.reason
     *
     * @param reason the value for ku_credit.reason
     *
     * @mbg.generated Mon Dec 11 10:54:47 CST 2017
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_credit.addtime
     *
     * @return the value of ku_credit.addtime
     *
     * @mbg.generated Mon Dec 11 10:54:47 CST 2017
     */
    public Integer getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_credit.addtime
     *
     * @param addtime the value for ku_credit.addtime
     *
     * @mbg.generated Mon Dec 11 10:54:47 CST 2017
     */
    public void setAddtime(Integer addtime) {
        this.addtime = addtime;
    }
}