package com.kuheng.entity.member;

import java.io.Serializable;

public class KuEvaluate implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_evaluate.itemid
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private Integer itemid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_evaluate.score
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private Integer score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_evaluate.selecttype
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private Integer selecttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_evaluate.orderid
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private Long orderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_evaluate.userid
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_evaluate.driverid
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private Long driverid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_evaluate.iswrite
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private Integer iswrite;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_evaluate.tag
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private String tag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_evaluate.content
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_evaluate.addtime
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private Integer addtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_evaluate.ip
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_evaluate.status
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private Boolean status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_evaluate.itemid
     *
     * @return the value of ku_evaluate.itemid
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public Integer getItemid() {
        return itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_evaluate.itemid
     *
     * @param itemid the value for ku_evaluate.itemid
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setItemid(Integer itemid) {
        this.itemid = itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_evaluate.score
     *
     * @return the value of ku_evaluate.score
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_evaluate.score
     *
     * @param score the value for ku_evaluate.score
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_evaluate.selecttype
     *
     * @return the value of ku_evaluate.selecttype
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public Integer getSelecttype() {
        return selecttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_evaluate.selecttype
     *
     * @param selecttype the value for ku_evaluate.selecttype
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setSelecttype(Integer selecttype) {
        this.selecttype = selecttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_evaluate.orderid
     *
     * @return the value of ku_evaluate.orderid
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public Long getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_evaluate.orderid
     *
     * @param orderid the value for ku_evaluate.orderid
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setOrderid(Long orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_evaluate.userid
     *
     * @return the value of ku_evaluate.userid
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_evaluate.userid
     *
     * @param userid the value for ku_evaluate.userid
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_evaluate.driverid
     *
     * @return the value of ku_evaluate.driverid
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public Long getDriverid() {
        return driverid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_evaluate.driverid
     *
     * @param driverid the value for ku_evaluate.driverid
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setDriverid(Long driverid) {
        this.driverid = driverid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_evaluate.iswrite
     *
     * @return the value of ku_evaluate.iswrite
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public Integer getIswrite() {
        return iswrite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_evaluate.iswrite
     *
     * @param iswrite the value for ku_evaluate.iswrite
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setIswrite(Integer iswrite) {
        this.iswrite = iswrite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_evaluate.tag
     *
     * @return the value of ku_evaluate.tag
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_evaluate.tag
     *
     * @param tag the value for ku_evaluate.tag
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setTag(String tag) {
        this.tag = tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_evaluate.content
     *
     * @return the value of ku_evaluate.content
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_evaluate.content
     *
     * @param content the value for ku_evaluate.content
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_evaluate.addtime
     *
     * @return the value of ku_evaluate.addtime
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public Integer getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_evaluate.addtime
     *
     * @param addtime the value for ku_evaluate.addtime
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setAddtime(Integer addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_evaluate.ip
     *
     * @return the value of ku_evaluate.ip
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_evaluate.ip
     *
     * @param ip the value for ku_evaluate.ip
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_evaluate.status
     *
     * @return the value of ku_evaluate.status
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_evaluate.status
     *
     * @param status the value for ku_evaluate.status
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }
}