package com.kuheng.entity.member;

import java.io.Serializable;
import java.math.BigDecimal;

public class KuJob implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_job.itemid
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private Integer itemid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_job.userid
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_job.truename
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private String truename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_job.mobile
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_job.sex
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private Short sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_job.birthday
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private String birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_job.cartype
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private Short cartype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_job.caryear
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private Integer caryear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_job.money
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private BigDecimal money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_job.areaid
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private Integer areaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_job.state
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private Byte state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_job.addtime
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private Integer addtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_job.itemid
     *
     * @return the value of ku_job.itemid
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public Integer getItemid() {
        return itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_job.itemid
     *
     * @param itemid the value for ku_job.itemid
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setItemid(Integer itemid) {
        this.itemid = itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_job.userid
     *
     * @return the value of ku_job.userid
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_job.userid
     *
     * @param userid the value for ku_job.userid
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_job.truename
     *
     * @return the value of ku_job.truename
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public String getTruename() {
        return truename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_job.truename
     *
     * @param truename the value for ku_job.truename
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setTruename(String truename) {
        this.truename = truename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_job.mobile
     *
     * @return the value of ku_job.mobile
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_job.mobile
     *
     * @param mobile the value for ku_job.mobile
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_job.sex
     *
     * @return the value of ku_job.sex
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public Short getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_job.sex
     *
     * @param sex the value for ku_job.sex
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setSex(Short sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_job.birthday
     *
     * @return the value of ku_job.birthday
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_job.birthday
     *
     * @param birthday the value for ku_job.birthday
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_job.cartype
     *
     * @return the value of ku_job.cartype
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public Short getCartype() {
        return cartype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_job.cartype
     *
     * @param cartype the value for ku_job.cartype
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setCartype(Short cartype) {
        this.cartype = cartype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_job.caryear
     *
     * @return the value of ku_job.caryear
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public Integer getCaryear() {
        return caryear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_job.caryear
     *
     * @param caryear the value for ku_job.caryear
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setCaryear(Integer caryear) {
        this.caryear = caryear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_job.money
     *
     * @return the value of ku_job.money
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_job.money
     *
     * @param money the value for ku_job.money
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_job.areaid
     *
     * @return the value of ku_job.areaid
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public Integer getAreaid() {
        return areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_job.areaid
     *
     * @param areaid the value for ku_job.areaid
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setAreaid(Integer areaid) {
        this.areaid = areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_job.state
     *
     * @return the value of ku_job.state
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_job.state
     *
     * @param state the value for ku_job.state
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_job.addtime
     *
     * @return the value of ku_job.addtime
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public Integer getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_job.addtime
     *
     * @param addtime the value for ku_job.addtime
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setAddtime(Integer addtime) {
        this.addtime = addtime;
    }
}