package com.kuheng.entity.member;

public class KuLoan {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_loan.itemid
     *
     * @mbg.generated Sat Dec 16 16:34:02 CST 2017
     */
    private Integer itemid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_loan.userid
     *
     * @mbg.generated Sat Dec 16 16:34:02 CST 2017
     */
    private Long userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_loan.reason
     *
     * @mbg.generated Sat Dec 16 16:34:02 CST 2017
     */
    private String reason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_loan.money
     *
     * @mbg.generated Sat Dec 16 16:34:02 CST 2017
     */
    private String money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_loan.limittime
     *
     * @mbg.generated Sat Dec 16 16:34:02 CST 2017
     */
    private String limittime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_loan.addtime
     *
     * @mbg.generated Sat Dec 16 16:34:02 CST 2017
     */
    private Integer addtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_loan.itemid
     *
     * @return the value of ku_loan.itemid
     *
     * @mbg.generated Sat Dec 16 16:34:02 CST 2017
     */
    public Integer getItemid() {
        return itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_loan.itemid
     *
     * @param itemid the value for ku_loan.itemid
     *
     * @mbg.generated Sat Dec 16 16:34:02 CST 2017
     */
    public void setItemid(Integer itemid) {
        this.itemid = itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_loan.userid
     *
     * @return the value of ku_loan.userid
     *
     * @mbg.generated Sat Dec 16 16:34:02 CST 2017
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_loan.userid
     *
     * @param userid the value for ku_loan.userid
     *
     * @mbg.generated Sat Dec 16 16:34:02 CST 2017
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_loan.reason
     *
     * @return the value of ku_loan.reason
     *
     * @mbg.generated Sat Dec 16 16:34:02 CST 2017
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_loan.reason
     *
     * @param reason the value for ku_loan.reason
     *
     * @mbg.generated Sat Dec 16 16:34:02 CST 2017
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_loan.money
     *
     * @return the value of ku_loan.money
     *
     * @mbg.generated Sat Dec 16 16:34:02 CST 2017
     */
    public String getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_loan.money
     *
     * @param money the value for ku_loan.money
     *
     * @mbg.generated Sat Dec 16 16:34:02 CST 2017
     */
    public void setMoney(String money) {
        this.money = money == null ? null : money.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_loan.limittime
     *
     * @return the value of ku_loan.limittime
     *
     * @mbg.generated Sat Dec 16 16:34:02 CST 2017
     */
    public String getLimittime() {
        return limittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_loan.limittime
     *
     * @param limittime the value for ku_loan.limittime
     *
     * @mbg.generated Sat Dec 16 16:34:02 CST 2017
     */
    public void setLimittime(String limittime) {
        this.limittime = limittime == null ? null : limittime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_loan.addtime
     *
     * @return the value of ku_loan.addtime
     *
     * @mbg.generated Sat Dec 16 16:34:02 CST 2017
     */
    public Integer getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_loan.addtime
     *
     * @param addtime the value for ku_loan.addtime
     *
     * @mbg.generated Sat Dec 16 16:34:02 CST 2017
     */
    public void setAddtime(Integer addtime) {
        this.addtime = addtime;
    }
}