package com.kuheng.entity.member;

import java.io.Serializable;
import java.math.BigDecimal;

public class KuMember implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_member.userid
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_member.mobile
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_member.company
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private String company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_member.password
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_member.pwdsafe
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private Short pwdsafe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_member.gender
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private Byte gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_member.truename
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private String truename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_member.idno
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private String idno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_member.headphoto
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private String headphoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_member.allcredit
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private Integer allcredit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_member.credit
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private Integer credit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_member.money
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private BigDecimal money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_member.areaid
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private Integer areaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_member.address
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_member.telephone
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_member.edittime
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private Integer edittime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_member.regip
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private String regip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_member.regtime
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private Integer regtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_member.loginip
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private String loginip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_member.logintime
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private Integer logintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_member.lastlogintime
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private Integer lastlogintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_member.logintimes
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private Integer logintimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_member.secretkey
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private String secretkey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_member.token
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_member.vmobile
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private Byte vmobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_member.validated
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private Byte validated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_member.validtime
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private Integer validtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_member.status
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_member.smallnum1
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private String smallnum1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_member.smallnum2
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private String smallnum2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_member.mobile2
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private String mobile2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_member.mobile3
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private String mobile3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_member.userid
     *
     * @return the value of ku_member.userid
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_member.userid
     *
     * @param userid the value for ku_member.userid
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_member.mobile
     *
     * @return the value of ku_member.mobile
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_member.mobile
     *
     * @param mobile the value for ku_member.mobile
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_member.company
     *
     * @return the value of ku_member.company
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_member.company
     *
     * @param company the value for ku_member.company
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setCompany(String company) {
        this.company = company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_member.password
     *
     * @return the value of ku_member.password
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_member.password
     *
     * @param password the value for ku_member.password
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_member.pwdsafe
     *
     * @return the value of ku_member.pwdsafe
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public Short getPwdsafe() {
        return pwdsafe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_member.pwdsafe
     *
     * @param pwdsafe the value for ku_member.pwdsafe
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setPwdsafe(Short pwdsafe) {
        this.pwdsafe = pwdsafe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_member.gender
     *
     * @return the value of ku_member.gender
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public Byte getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_member.gender
     *
     * @param gender the value for ku_member.gender
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setGender(Byte gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_member.truename
     *
     * @return the value of ku_member.truename
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public String getTruename() {
        return truename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_member.truename
     *
     * @param truename the value for ku_member.truename
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setTruename(String truename) {
        this.truename = truename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_member.idno
     *
     * @return the value of ku_member.idno
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public String getIdno() {
        return idno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_member.idno
     *
     * @param idno the value for ku_member.idno
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setIdno(String idno) {
        this.idno = idno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_member.headphoto
     *
     * @return the value of ku_member.headphoto
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public String getHeadphoto() {
        return headphoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_member.headphoto
     *
     * @param headphoto the value for ku_member.headphoto
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setHeadphoto(String headphoto) {
        this.headphoto = headphoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_member.allcredit
     *
     * @return the value of ku_member.allcredit
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public Integer getAllcredit() {
        return allcredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_member.allcredit
     *
     * @param allcredit the value for ku_member.allcredit
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setAllcredit(Integer allcredit) {
        this.allcredit = allcredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_member.credit
     *
     * @return the value of ku_member.credit
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public Integer getCredit() {
        return credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_member.credit
     *
     * @param credit the value for ku_member.credit
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setCredit(Integer credit) {
        this.credit = credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_member.money
     *
     * @return the value of ku_member.money
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_member.money
     *
     * @param money the value for ku_member.money
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_member.areaid
     *
     * @return the value of ku_member.areaid
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public Integer getAreaid() {
        return areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_member.areaid
     *
     * @param areaid the value for ku_member.areaid
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setAreaid(Integer areaid) {
        this.areaid = areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_member.address
     *
     * @return the value of ku_member.address
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_member.address
     *
     * @param address the value for ku_member.address
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_member.telephone
     *
     * @return the value of ku_member.telephone
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_member.telephone
     *
     * @param telephone the value for ku_member.telephone
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_member.edittime
     *
     * @return the value of ku_member.edittime
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public Integer getEdittime() {
        return edittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_member.edittime
     *
     * @param edittime the value for ku_member.edittime
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setEdittime(Integer edittime) {
        this.edittime = edittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_member.regip
     *
     * @return the value of ku_member.regip
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public String getRegip() {
        return regip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_member.regip
     *
     * @param regip the value for ku_member.regip
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setRegip(String regip) {
        this.regip = regip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_member.regtime
     *
     * @return the value of ku_member.regtime
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public Integer getRegtime() {
        return regtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_member.regtime
     *
     * @param regtime the value for ku_member.regtime
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setRegtime(Integer regtime) {
        this.regtime = regtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_member.loginip
     *
     * @return the value of ku_member.loginip
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public String getLoginip() {
        return loginip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_member.loginip
     *
     * @param loginip the value for ku_member.loginip
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setLoginip(String loginip) {
        this.loginip = loginip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_member.logintime
     *
     * @return the value of ku_member.logintime
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public Integer getLogintime() {
        return logintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_member.logintime
     *
     * @param logintime the value for ku_member.logintime
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setLogintime(Integer logintime) {
        this.logintime = logintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_member.lastlogintime
     *
     * @return the value of ku_member.lastlogintime
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public Integer getLastlogintime() {
        return lastlogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_member.lastlogintime
     *
     * @param lastlogintime the value for ku_member.lastlogintime
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setLastlogintime(Integer lastlogintime) {
        this.lastlogintime = lastlogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_member.logintimes
     *
     * @return the value of ku_member.logintimes
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public Integer getLogintimes() {
        return logintimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_member.logintimes
     *
     * @param logintimes the value for ku_member.logintimes
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setLogintimes(Integer logintimes) {
        this.logintimes = logintimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_member.secretkey
     *
     * @return the value of ku_member.secretkey
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public String getSecretkey() {
        return secretkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_member.secretkey
     *
     * @param secretkey the value for ku_member.secretkey
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setSecretkey(String secretkey) {
        this.secretkey = secretkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_member.token
     *
     * @return the value of ku_member.token
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_member.token
     *
     * @param token the value for ku_member.token
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setToken(String token) {
        this.token = token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_member.vmobile
     *
     * @return the value of ku_member.vmobile
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public Byte getVmobile() {
        return vmobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_member.vmobile
     *
     * @param vmobile the value for ku_member.vmobile
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setVmobile(Byte vmobile) {
        this.vmobile = vmobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_member.validated
     *
     * @return the value of ku_member.validated
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public Byte getValidated() {
        return validated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_member.validated
     *
     * @param validated the value for ku_member.validated
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setValidated(Byte validated) {
        this.validated = validated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_member.validtime
     *
     * @return the value of ku_member.validtime
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public Integer getValidtime() {
        return validtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_member.validtime
     *
     * @param validtime the value for ku_member.validtime
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setValidtime(Integer validtime) {
        this.validtime = validtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_member.status
     *
     * @return the value of ku_member.status
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_member.status
     *
     * @param status the value for ku_member.status
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_member.smallnum1
     *
     * @return the value of ku_member.smallnum1
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public String getSmallnum1() {
        return smallnum1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_member.smallnum1
     *
     * @param smallnum1 the value for ku_member.smallnum1
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setSmallnum1(String smallnum1) {
        this.smallnum1 = smallnum1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_member.smallnum2
     *
     * @return the value of ku_member.smallnum2
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public String getSmallnum2() {
        return smallnum2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_member.smallnum2
     *
     * @param smallnum2 the value for ku_member.smallnum2
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setSmallnum2(String smallnum2) {
        this.smallnum2 = smallnum2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_member.mobile2
     *
     * @return the value of ku_member.mobile2
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public String getMobile2() {
        return mobile2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_member.mobile2
     *
     * @param mobile2 the value for ku_member.mobile2
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setMobile2(String mobile2) {
        this.mobile2 = mobile2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_member.mobile3
     *
     * @return the value of ku_member.mobile3
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public String getMobile3() {
        return mobile3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_member.mobile3
     *
     * @param mobile3 the value for ku_member.mobile3
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setMobile3(String mobile3) {
        this.mobile3 = mobile3;
    }
}