package com.kuheng.entity.member;

public class KuMessage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_message.itemid
     *
     * @mbggenerated Thu Jul 20 16:25:48 CST 2017
     */
    private Integer itemid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_message.type
     *
     * @mbggenerated Thu Jul 20 16:25:48 CST 2017
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_message.title
     *
     * @mbggenerated Thu Jul 20 16:25:48 CST 2017
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_message.content
     *
     * @mbggenerated Thu Jul 20 16:25:48 CST 2017
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_message.touserid
     *
     * @mbggenerated Thu Jul 20 16:25:48 CST 2017
     */
    private Integer touserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_message.ip
     *
     * @mbggenerated Thu Jul 20 16:25:48 CST 2017
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_message.addtime
     *
     * @mbggenerated Thu Jul 20 16:25:48 CST 2017
     */
    private Integer addtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_message.itemid
     *
     * @return the value of ku_message.itemid
     *
     * @mbggenerated Thu Jul 20 16:25:48 CST 2017
     */
    public Integer getItemid() {
        return itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_message.itemid
     *
     * @param itemid the value for ku_message.itemid
     *
     * @mbggenerated Thu Jul 20 16:25:48 CST 2017
     */
    public void setItemid(Integer itemid) {
        this.itemid = itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_message.type
     *
     * @return the value of ku_message.type
     *
     * @mbggenerated Thu Jul 20 16:25:48 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_message.type
     *
     * @param type the value for ku_message.type
     *
     * @mbggenerated Thu Jul 20 16:25:48 CST 2017
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_message.title
     *
     * @return the value of ku_message.title
     *
     * @mbggenerated Thu Jul 20 16:25:48 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_message.title
     *
     * @param title the value for ku_message.title
     *
     * @mbggenerated Thu Jul 20 16:25:48 CST 2017
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_message.content
     *
     * @return the value of ku_message.content
     *
     * @mbggenerated Thu Jul 20 16:25:48 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_message.content
     *
     * @param content the value for ku_message.content
     *
     * @mbggenerated Thu Jul 20 16:25:48 CST 2017
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_message.touserid
     *
     * @return the value of ku_message.touserid
     *
     * @mbggenerated Thu Jul 20 16:25:48 CST 2017
     */
    public Integer getTouserid() {
        return touserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_message.touserid
     *
     * @param touserid the value for ku_message.touserid
     *
     * @mbggenerated Thu Jul 20 16:25:48 CST 2017
     */
    public void setTouserid(Integer touserid) {
        this.touserid = touserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_message.ip
     *
     * @return the value of ku_message.ip
     *
     * @mbggenerated Thu Jul 20 16:25:48 CST 2017
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_message.ip
     *
     * @param ip the value for ku_message.ip
     *
     * @mbggenerated Thu Jul 20 16:25:48 CST 2017
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_message.addtime
     *
     * @return the value of ku_message.addtime
     *
     * @mbggenerated Thu Jul 20 16:25:48 CST 2017
     */
    public Integer getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_message.addtime
     *
     * @param addtime the value for ku_message.addtime
     *
     * @mbggenerated Thu Jul 20 16:25:48 CST 2017
     */
    public void setAddtime(Integer addtime) {
        this.addtime = addtime;
    }
}