package com.kuheng.entity.member;

import java.io.Serializable;
import java.math.BigDecimal;

public class KuOrders implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_orders.ID
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_orders.ordersid
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    private Long ordersid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_orders.userid
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_orders.sendcompany
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    private String sendcompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_orders.sendrealname
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    private String sendrealname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_orders.sendmobile
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    private String sendmobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_orders.sendarea
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    private Integer sendarea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_orders.sendaddress
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    private String sendaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_orders.recarea
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    private Integer recarea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_orders.recaddress
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    private String recaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_orders.title
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_orders.allfee
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    private BigDecimal allfee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_orders.goodsnote
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    private String goodsnote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_orders.otherservice
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    private String otherservice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_orders.runstatus
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    private String runstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_orders.expecttime
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    private Integer expecttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_orders.payway
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    private Integer payway;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_orders.addtime
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    private Integer addtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_orders.updatetime
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    private Integer updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_orders.signtime
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    private Integer signtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_orders.delstatus
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    private Integer delstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_orders.evaluation
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    private Integer evaluation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_orders.transportbyid
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    private Integer transportbyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_orders.editer
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    private String editer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_orders.longitude
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    private BigDecimal longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_orders.latitude
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    private BigDecimal latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_orders.ip
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_orders.status
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_orders.infotype
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    private Integer infotype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_orders.Msg_Sign
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    private Integer msgSign;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_orders.ID
     *
     * @return the value of ku_orders.ID
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_orders.ID
     *
     * @param id the value for ku_orders.ID
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_orders.ordersid
     *
     * @return the value of ku_orders.ordersid
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    public Long getOrdersid() {
        return ordersid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_orders.ordersid
     *
     * @param ordersid the value for ku_orders.ordersid
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    public void setOrdersid(Long ordersid) {
        this.ordersid = ordersid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_orders.userid
     *
     * @return the value of ku_orders.userid
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_orders.userid
     *
     * @param userid the value for ku_orders.userid
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_orders.sendcompany
     *
     * @return the value of ku_orders.sendcompany
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    public String getSendcompany() {
        return sendcompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_orders.sendcompany
     *
     * @param sendcompany the value for ku_orders.sendcompany
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    public void setSendcompany(String sendcompany) {
        this.sendcompany = sendcompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_orders.sendrealname
     *
     * @return the value of ku_orders.sendrealname
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    public String getSendrealname() {
        return sendrealname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_orders.sendrealname
     *
     * @param sendrealname the value for ku_orders.sendrealname
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    public void setSendrealname(String sendrealname) {
        this.sendrealname = sendrealname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_orders.sendmobile
     *
     * @return the value of ku_orders.sendmobile
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    public String getSendmobile() {
        return sendmobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_orders.sendmobile
     *
     * @param sendmobile the value for ku_orders.sendmobile
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    public void setSendmobile(String sendmobile) {
        this.sendmobile = sendmobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_orders.sendarea
     *
     * @return the value of ku_orders.sendarea
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    public Integer getSendarea() {
        return sendarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_orders.sendarea
     *
     * @param sendarea the value for ku_orders.sendarea
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    public void setSendarea(Integer sendarea) {
        this.sendarea = sendarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_orders.sendaddress
     *
     * @return the value of ku_orders.sendaddress
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    public String getSendaddress() {
        return sendaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_orders.sendaddress
     *
     * @param sendaddress the value for ku_orders.sendaddress
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    public void setSendaddress(String sendaddress) {
        this.sendaddress = sendaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_orders.recarea
     *
     * @return the value of ku_orders.recarea
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    public Integer getRecarea() {
        return recarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_orders.recarea
     *
     * @param recarea the value for ku_orders.recarea
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    public void setRecarea(Integer recarea) {
        this.recarea = recarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_orders.recaddress
     *
     * @return the value of ku_orders.recaddress
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    public String getRecaddress() {
        return recaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_orders.recaddress
     *
     * @param recaddress the value for ku_orders.recaddress
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    public void setRecaddress(String recaddress) {
        this.recaddress = recaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_orders.title
     *
     * @return the value of ku_orders.title
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_orders.title
     *
     * @param title the value for ku_orders.title
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_orders.allfee
     *
     * @return the value of ku_orders.allfee
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    public BigDecimal getAllfee() {
        return allfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_orders.allfee
     *
     * @param allfee the value for ku_orders.allfee
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    public void setAllfee(BigDecimal allfee) {
        this.allfee = allfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_orders.goodsnote
     *
     * @return the value of ku_orders.goodsnote
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    public String getGoodsnote() {
        return goodsnote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_orders.goodsnote
     *
     * @param goodsnote the value for ku_orders.goodsnote
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    public void setGoodsnote(String goodsnote) {
        this.goodsnote = goodsnote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_orders.otherservice
     *
     * @return the value of ku_orders.otherservice
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    public String getOtherservice() {
        return otherservice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_orders.otherservice
     *
     * @param otherservice the value for ku_orders.otherservice
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    public void setOtherservice(String otherservice) {
        this.otherservice = otherservice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_orders.runstatus
     *
     * @return the value of ku_orders.runstatus
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    public String getRunstatus() {
        return runstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_orders.runstatus
     *
     * @param runstatus the value for ku_orders.runstatus
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    public void setRunstatus(String runstatus) {
        this.runstatus = runstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_orders.expecttime
     *
     * @return the value of ku_orders.expecttime
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    public Integer getExpecttime() {
        return expecttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_orders.expecttime
     *
     * @param expecttime the value for ku_orders.expecttime
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    public void setExpecttime(Integer expecttime) {
        this.expecttime = expecttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_orders.payway
     *
     * @return the value of ku_orders.payway
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    public Integer getPayway() {
        return payway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_orders.payway
     *
     * @param payway the value for ku_orders.payway
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    public void setPayway(Integer payway) {
        this.payway = payway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_orders.addtime
     *
     * @return the value of ku_orders.addtime
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    public Integer getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_orders.addtime
     *
     * @param addtime the value for ku_orders.addtime
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    public void setAddtime(Integer addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_orders.updatetime
     *
     * @return the value of ku_orders.updatetime
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    public Integer getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_orders.updatetime
     *
     * @param updatetime the value for ku_orders.updatetime
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    public void setUpdatetime(Integer updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_orders.signtime
     *
     * @return the value of ku_orders.signtime
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    public Integer getSigntime() {
        return signtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_orders.signtime
     *
     * @param signtime the value for ku_orders.signtime
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    public void setSigntime(Integer signtime) {
        this.signtime = signtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_orders.delstatus
     *
     * @return the value of ku_orders.delstatus
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    public Integer getDelstatus() {
        return delstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_orders.delstatus
     *
     * @param delstatus the value for ku_orders.delstatus
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    public void setDelstatus(Integer delstatus) {
        this.delstatus = delstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_orders.evaluation
     *
     * @return the value of ku_orders.evaluation
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    public Integer getEvaluation() {
        return evaluation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_orders.evaluation
     *
     * @param evaluation the value for ku_orders.evaluation
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    public void setEvaluation(Integer evaluation) {
        this.evaluation = evaluation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_orders.transportbyid
     *
     * @return the value of ku_orders.transportbyid
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    public Integer getTransportbyid() {
        return transportbyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_orders.transportbyid
     *
     * @param transportbyid the value for ku_orders.transportbyid
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    public void setTransportbyid(Integer transportbyid) {
        this.transportbyid = transportbyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_orders.editer
     *
     * @return the value of ku_orders.editer
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    public String getEditer() {
        return editer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_orders.editer
     *
     * @param editer the value for ku_orders.editer
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    public void setEditer(String editer) {
        this.editer = editer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_orders.longitude
     *
     * @return the value of ku_orders.longitude
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    public BigDecimal getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_orders.longitude
     *
     * @param longitude the value for ku_orders.longitude
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    public void setLongitude(BigDecimal longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_orders.latitude
     *
     * @return the value of ku_orders.latitude
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    public BigDecimal getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_orders.latitude
     *
     * @param latitude the value for ku_orders.latitude
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    public void setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_orders.ip
     *
     * @return the value of ku_orders.ip
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_orders.ip
     *
     * @param ip the value for ku_orders.ip
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_orders.status
     *
     * @return the value of ku_orders.status
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_orders.status
     *
     * @param status the value for ku_orders.status
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_orders.infotype
     *
     * @return the value of ku_orders.infotype
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    public Integer getInfotype() {
        return infotype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_orders.infotype
     *
     * @param infotype the value for ku_orders.infotype
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    public void setInfotype(Integer infotype) {
        this.infotype = infotype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_orders.Msg_Sign
     *
     * @return the value of ku_orders.Msg_Sign
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    public Integer getMsgSign() {
        return msgSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_orders.Msg_Sign
     *
     * @param msgSign the value for ku_orders.Msg_Sign
     *
     * @mbggenerated Wed Jun 28 10:34:14 CST 2017
     */
    public void setMsgSign(Integer msgSign) {
        this.msgSign = msgSign;
    }
}