package com.kuheng.entity.member;

public class KuSendmsgLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_sendmsg_log.itemid
     *
     * @mbg.generated Fri Sep 22 09:38:15 CST 2017
     */
    private Integer itemid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_sendmsg_log.mobile
     *
     * @mbg.generated Fri Sep 22 09:38:15 CST 2017
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_sendmsg_log.title
     *
     * @mbg.generated Fri Sep 22 09:38:15 CST 2017
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_sendmsg_log.apptype
     *
     * @mbg.generated Fri Sep 22 09:38:15 CST 2017
     */
    private Integer apptype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_sendmsg_log.note
     *
     * @mbg.generated Fri Sep 22 09:38:15 CST 2017
     */
    private String note;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_sendmsg_log.code
     *
     * @mbg.generated Fri Sep 22 09:38:15 CST 2017
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_sendmsg_log.ip
     *
     * @mbg.generated Fri Sep 22 09:38:15 CST 2017
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_sendmsg_log.status
     *
     * @mbg.generated Fri Sep 22 09:38:15 CST 2017
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_sendmsg_log.addtime
     *
     * @mbg.generated Fri Sep 22 09:38:15 CST 2017
     */
    private Integer addtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_sendmsg_log.itemid
     *
     * @return the value of ku_sendmsg_log.itemid
     *
     * @mbg.generated Fri Sep 22 09:38:15 CST 2017
     */
    public Integer getItemid() {
        return itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_sendmsg_log.itemid
     *
     * @param itemid the value for ku_sendmsg_log.itemid
     *
     * @mbg.generated Fri Sep 22 09:38:15 CST 2017
     */
    public void setItemid(Integer itemid) {
        this.itemid = itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_sendmsg_log.mobile
     *
     * @return the value of ku_sendmsg_log.mobile
     *
     * @mbg.generated Fri Sep 22 09:38:15 CST 2017
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_sendmsg_log.mobile
     *
     * @param mobile the value for ku_sendmsg_log.mobile
     *
     * @mbg.generated Fri Sep 22 09:38:15 CST 2017
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_sendmsg_log.title
     *
     * @return the value of ku_sendmsg_log.title
     *
     * @mbg.generated Fri Sep 22 09:38:15 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_sendmsg_log.title
     *
     * @param title the value for ku_sendmsg_log.title
     *
     * @mbg.generated Fri Sep 22 09:38:15 CST 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_sendmsg_log.apptype
     *
     * @return the value of ku_sendmsg_log.apptype
     *
     * @mbg.generated Fri Sep 22 09:38:15 CST 2017
     */
    public Integer getApptype() {
        return apptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_sendmsg_log.apptype
     *
     * @param apptype the value for ku_sendmsg_log.apptype
     *
     * @mbg.generated Fri Sep 22 09:38:15 CST 2017
     */
    public void setApptype(Integer apptype) {
        this.apptype = apptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_sendmsg_log.note
     *
     * @return the value of ku_sendmsg_log.note
     *
     * @mbg.generated Fri Sep 22 09:38:15 CST 2017
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_sendmsg_log.note
     *
     * @param note the value for ku_sendmsg_log.note
     *
     * @mbg.generated Fri Sep 22 09:38:15 CST 2017
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_sendmsg_log.code
     *
     * @return the value of ku_sendmsg_log.code
     *
     * @mbg.generated Fri Sep 22 09:38:15 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_sendmsg_log.code
     *
     * @param code the value for ku_sendmsg_log.code
     *
     * @mbg.generated Fri Sep 22 09:38:15 CST 2017
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_sendmsg_log.ip
     *
     * @return the value of ku_sendmsg_log.ip
     *
     * @mbg.generated Fri Sep 22 09:38:15 CST 2017
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_sendmsg_log.ip
     *
     * @param ip the value for ku_sendmsg_log.ip
     *
     * @mbg.generated Fri Sep 22 09:38:15 CST 2017
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_sendmsg_log.status
     *
     * @return the value of ku_sendmsg_log.status
     *
     * @mbg.generated Fri Sep 22 09:38:15 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_sendmsg_log.status
     *
     * @param status the value for ku_sendmsg_log.status
     *
     * @mbg.generated Fri Sep 22 09:38:15 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_sendmsg_log.addtime
     *
     * @return the value of ku_sendmsg_log.addtime
     *
     * @mbg.generated Fri Sep 22 09:38:15 CST 2017
     */
    public Integer getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_sendmsg_log.addtime
     *
     * @param addtime the value for ku_sendmsg_log.addtime
     *
     * @mbg.generated Fri Sep 22 09:38:15 CST 2017
     */
    public void setAddtime(Integer addtime) {
        this.addtime = addtime;
    }
}