package com.kuheng.entity.member;

import java.io.Serializable;

public class KuSiteCategory implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_site_category.itemid
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private Integer itemid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_site_category.title
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_site_category.amount
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private Integer amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_site_category.pinyin
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private String pinyin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_site_category.letter
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private String letter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_site_category.level
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private Boolean level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_site_category.parentid
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private Integer parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_site_category.listorder
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private Short listorder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_site_category.logo
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private String logo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_site_category.seotitle
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private String seotitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_site_category.seokeywords
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private String seokeywords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ku_site_category.seodescription
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    private String seodescription;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_site_category.itemid
     *
     * @return the value of ku_site_category.itemid
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public Integer getItemid() {
        return itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_site_category.itemid
     *
     * @param itemid the value for ku_site_category.itemid
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setItemid(Integer itemid) {
        this.itemid = itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_site_category.title
     *
     * @return the value of ku_site_category.title
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_site_category.title
     *
     * @param title the value for ku_site_category.title
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_site_category.amount
     *
     * @return the value of ku_site_category.amount
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_site_category.amount
     *
     * @param amount the value for ku_site_category.amount
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_site_category.pinyin
     *
     * @return the value of ku_site_category.pinyin
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public String getPinyin() {
        return pinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_site_category.pinyin
     *
     * @param pinyin the value for ku_site_category.pinyin
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setPinyin(String pinyin) {
        this.pinyin = pinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_site_category.letter
     *
     * @return the value of ku_site_category.letter
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public String getLetter() {
        return letter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_site_category.letter
     *
     * @param letter the value for ku_site_category.letter
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setLetter(String letter) {
        this.letter = letter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_site_category.level
     *
     * @return the value of ku_site_category.level
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public Boolean getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_site_category.level
     *
     * @param level the value for ku_site_category.level
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setLevel(Boolean level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_site_category.parentid
     *
     * @return the value of ku_site_category.parentid
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_site_category.parentid
     *
     * @param parentid the value for ku_site_category.parentid
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_site_category.listorder
     *
     * @return the value of ku_site_category.listorder
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public Short getListorder() {
        return listorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_site_category.listorder
     *
     * @param listorder the value for ku_site_category.listorder
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setListorder(Short listorder) {
        this.listorder = listorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_site_category.logo
     *
     * @return the value of ku_site_category.logo
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_site_category.logo
     *
     * @param logo the value for ku_site_category.logo
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setLogo(String logo) {
        this.logo = logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_site_category.seotitle
     *
     * @return the value of ku_site_category.seotitle
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public String getSeotitle() {
        return seotitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_site_category.seotitle
     *
     * @param seotitle the value for ku_site_category.seotitle
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setSeotitle(String seotitle) {
        this.seotitle = seotitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_site_category.seokeywords
     *
     * @return the value of ku_site_category.seokeywords
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public String getSeokeywords() {
        return seokeywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_site_category.seokeywords
     *
     * @param seokeywords the value for ku_site_category.seokeywords
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setSeokeywords(String seokeywords) {
        this.seokeywords = seokeywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ku_site_category.seodescription
     *
     * @return the value of ku_site_category.seodescription
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public String getSeodescription() {
        return seodescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ku_site_category.seodescription
     *
     * @param seodescription the value for ku_site_category.seodescription
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    public void setSeodescription(String seodescription) {
        this.seodescription = seodescription;
    }
}