package com.kuheng.dao;

import com.kuheng.entity.member.EInfo;

public interface EInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_info
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_info
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    int insert(EInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_info
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    int insertSelective(EInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_info
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    EInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_info
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    int updateByPrimaryKeySelective(EInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table e_info
     *
     * @mbg.generated Wed Sep 13 08:44:06 CST 2017
     */
    int updateByPrimaryKey(EInfo record);
}