package com.kuheng.dao;

import java.util.List;
import java.util.Map;

import com.kuheng.entity.member.KuAdmin;

public interface KuAdminMapper {
	 /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_admin
     *
     * @mbggenerated Mon May 22 08:41:46 CST 2017
     */
    int deleteByPrimaryKey(Integer adminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_admin
     *
     * @mbggenerated Mon May 22 08:41:46 CST 2017
     */
    int insert(KuAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_admin
     *
     * @mbggenerated Mon May 22 08:41:46 CST 2017
     */
    int insertSelective(KuAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_admin
     *
     * @mbggenerated Mon May 22 08:41:46 CST 2017
     */
    KuAdmin selectByPrimaryKey(Integer adminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_admin
     *
     * @mbggenerated Mon May 22 08:41:46 CST 2017
     */
    int updateByPrimaryKeySelective(KuAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_admin
     *
     * @mbggenerated Mon May 22 08:41:46 CST 2017
     */
    int updateByPrimaryKey(KuAdmin record);
    
    
    
    
    
    /**
	 * 获取用的信息通过用户名
	 */
	public KuAdmin selectByName(String  username);
    
	/**
	 * 按条件查询记录
	 * 
	 * @param param
	 *            查询条件参数，包括WHERE条件、分页条件、排序条件
	 * @return 符合条件记录的实体对象的List
	 */

	public List<KuAdmin> selectPaging(Map param); 
	
	
	
	/**
	 * 按条件查询记录总的记录
	 * 
	 * @param param
	 *    查询条件参数，包括WHERE条件、
	 */

	public int selectCount(Map param); 
}