package com.kuheng.dao;

import java.util.List;
import java.util.Map;

import com.kuheng.entity.member.KuCity;

public interface KuCityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_city
     *
     * @mbggenerated Sat May 20 15:02:04 CST 2017
     */
    int deleteByPrimaryKey(Integer areaid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_city
     *
     * @mbggenerated Sat May 20 15:02:04 CST 2017
     */
    int insert(KuCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_city
     *
     * @mbggenerated Sat May 20 15:02:04 CST 2017
     */
    int insertSelective(KuCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_city
     *
     * @mbggenerated Sat May 20 15:02:04 CST 2017
     */
    KuCity selectByPrimaryKey(Integer areaid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_city
     *
     * @mbggenerated Sat May 20 15:02:04 CST 2017
     */
    int updateByPrimaryKeySelective(KuCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_city
     *
     * @mbggenerated Sat May 20 15:02:04 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(KuCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_city
     *
     * @mbggenerated Sat May 20 15:02:04 CST 2017
     */
    int updateByPrimaryKey(KuCity record);
    
    
    
    
    /**
	 * 按条件查询记录
	 * 
	 * @param param
	 *            查询条件参数，包括WHERE条件、分页条件、排序条件
	 * @return 符合条件记录的实体对象的List
	 */

	public List<KuCity> selectPaging(Map param); 
	
	/**
	 * 按条件查询记录总的记录
	 * 
	 * @param param
	 *    查询条件参数，包括WHERE条件、
	 */

	public int selectCount(Map param); 

	
	
	/**
	 * 查询订阅路线起始地目的地的名称及上一级的名称（省-市-----省-市）
	 * 
	 * @param param
	 * @return
	 */
	public List<Map<String,Object>> selectProvinceAndCity(Map param);
	
	
	
	/**
	 * 查询订阅路线起始地目的地的名称及上一级的名称（省-市--县-----省-市-县）
	 * 
	 * @param param
	 * @return
	 */
	public List<Map<String,Object>> selectProvinceAndCity1(Map param);
	
	
	
	/**
	 * 查询订阅路线起始地目的地的名称及上一级的名称（省-市-----省-市-县）
	 * 
	 * @param param
	 * @return
	 */
	public List<Map<String,Object>> selectProvinceAndCity2(Map param);
	
	
	
	/**
	 * 查询订阅路线起始地目的地的名称及上一级的名称（省-市--县-----省-市）
	 * 
	 * @param param
	 * @return
	 */
	public List<Map<String,Object>> selectProvinceAndCity3(Map param);
	/**
	 * 按条件查询cityId
	 * 
	 * @param param
	 *    查询条件参数，包括省名、市名
	 */
	public int selectByMobileAddress(String province,String city);
	

	/**
	 * 查询注册的城市（2级）
	 * @param userid
	 * @return
	 */
	public List<Map<String,Object>> selectRegisterCity(Integer userid);
}