package com.kuheng.dao;

import java.util.List;
import java.util.Map;

import com.kuheng.entity.member.KuComplaint;
import com.kuheng.entity.member.KuDriver;

public interface KuDriverMapper {
	  /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_driver
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    int deleteByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_driver
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    int insert(KuDriver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_driver
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    int insertSelective(KuDriver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_driver
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    KuDriver selectByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_driver
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    int updateByPrimaryKeySelective(KuDriver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_driver
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    int updateByPrimaryKey(KuDriver record);
    
    
    
    
    /**
	 * 按条件查询记录
	 * 
	 * @param param
	 *            查询条件参数，包括WHERE条件、分页条件、排序条件
	 * @return 符合条件记录的实体对象的List
	 */

	public List<KuDriver> selectPaging(Map param); 
	
	
	
	/**
	 * 按条件查询记录总的记录
	 * 
	 * @param param
	 *    查询条件参数，包括WHERE条件、
	 */

	public int selectCount(Map param); 
	
	public List<Map<String,String>> selectAllCarno();
}