package com.kuheng.dao;

import java.util.List;
import java.util.Map;

import com.kuheng.entity.member.KuFriend;

public interface KuFriendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_friend
     *
     * @mbg.generated Wed Oct 11 16:13:17 CST 2017
     */
    int deleteByPrimaryKey(Integer itemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_friend
     *
     * @mbg.generated Wed Oct 11 16:13:17 CST 2017
     */
    int insert(KuFriend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_friend
     *
     * @mbg.generated Wed Oct 11 16:13:17 CST 2017
     */
    int insertSelective(KuFriend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_friend
     *
     * @mbg.generated Wed Oct 11 16:13:17 CST 2017
     */
    KuFriend selectByPrimaryKey(Integer itemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_friend
     *
     * @mbg.generated Wed Oct 11 16:13:17 CST 2017
     */
    int updateByPrimaryKeySelective(KuFriend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_friend
     *
     * @mbg.generated Wed Oct 11 16:13:17 CST 2017
     */
    int updateByPrimaryKey(KuFriend record);
    
    List<KuFriend> selectByUserId(long userId);
    
    List<Map<String,Object>> selectByUserId2(long userId);
}