package com.kuheng.dao;

import java.util.List;
import java.util.Map;

import com.kuheng.entity.member.KuKnowcar;

public interface KuKnowcarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_knowcar
     *
     * @mbg.generated Fri Sep 22 18:06:28 CST 2017
     */
    int deleteByPrimaryKey(Integer itemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_knowcar
     *
     * @mbg.generated Fri Sep 22 18:06:28 CST 2017
     */
    int insert(KuKnowcar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_knowcar
     *
     * @mbg.generated Fri Sep 22 18:06:28 CST 2017
     */
    int insertSelective(KuKnowcar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_knowcar
     *
     * @mbg.generated Fri Sep 22 18:06:28 CST 2017
     */
    KuKnowcar selectByPrimaryKey(Integer itemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_knowcar
     *
     * @mbg.generated Fri Sep 22 18:06:28 CST 2017
     */
    int updateByPrimaryKeySelective(KuKnowcar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_knowcar
     *
     * @mbg.generated Fri Sep 22 18:06:28 CST 2017
     */
    int updateByPrimaryKey(KuKnowcar record);
    /**
   	 * 按条件查询记录
   	 * 
   	 * @param param
   	 *            查询条件参数，包括WHERE条件、分页条件、排序条件
   	 * @return 符合条件记录的实体对象的List
   	 */
   	public List<Map<String,Object>> selectPaging(Map param); 
}