package com.kuheng.dao;

import com.kuheng.entity.member.KuLoan;

public interface KuLoanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_loan
     *
     * @mbg.generated Sat Dec 16 16:34:02 CST 2017
     */
    int deleteByPrimaryKey(Integer itemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_loan
     *
     * @mbg.generated Sat Dec 16 16:34:02 CST 2017
     */
    int insert(KuLoan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_loan
     *
     * @mbg.generated Sat Dec 16 16:34:02 CST 2017
     */
    int insertSelective(KuLoan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_loan
     *
     * @mbg.generated Sat Dec 16 16:34:02 CST 2017
     */
    KuLoan selectByPrimaryKey(Integer itemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_loan
     *
     * @mbg.generated Sat Dec 16 16:34:02 CST 2017
     */
    int updateByPrimaryKeySelective(KuLoan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_loan
     *
     * @mbg.generated Sat Dec 16 16:34:02 CST 2017
     */
    int updateByPrimaryKey(KuLoan record);
}