package com.kuheng.dao;

import java.util.List;
import java.util.Map;

import com.kuheng.entity.member.KuJob;
import com.kuheng.entity.member.KuMainline;

public interface KuMainlineMapper {
	  /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_mainline
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    int deleteByPrimaryKey(Integer itemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_mainline
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    int insert(KuMainline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_mainline
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    int insertSelective(KuMainline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_mainline
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    KuMainline selectByPrimaryKey(Integer itemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_mainline
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    int updateByPrimaryKeySelective(KuMainline record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_mainline
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    int updateByPrimaryKey(KuMainline record);
    
    
    
    /**
	 * 按条件查询记录
	 * 
	 * @param param
	 *            查询条件参数，包括WHERE条件、分页条件、排序条件
	 * @return 符合条件记录的实体对象的List
	 */

	public List<KuMainline> selectPaging(Map param); 
	
	 /**
		 * 按条件查询记录
		 * 
		 * @param param
		 *            查询条件参数(会员ID)
		 * @return 符合条件记录的实体对象的List
		 */

	public List<Map<String,Object>> selectByUserId(Integer userid); 
	/**
	 	 * 按条件查询记录
	 	 * @param userid
	 	 * @return 符合条件记录的实体对象的List(比上个方法多了两个地区的id及level)
	 	 */
	public List<Map<String,Object>> selectByUserId1(Integer userid);
	
	/**
	 * 按条件查询记录总的记录
	 * 
	 * @param param
	 *    查询条件参数，包括WHERE条件、
	 */

	public int selectCount(Map param); 
	
	/**
	 * 按会员查询记录总的记录
	 * 
	 * @param param
	 *    查询条件参数，包括WHERE条件、
	 */
	public int selectCountByUserId(Integer userid);
}