package com.kuheng.dao;

import java.util.List;
import java.util.Map;

import com.kuheng.entity.member.KuMember;

public interface KuMemberMapper {
	 /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_member
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    int deleteByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_member
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    int insert(KuMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_member
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    int insertSelective(KuMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_member
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    KuMember selectByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_member
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    int updateByPrimaryKeySelective(KuMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_member
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    int updateByPrimaryKey(KuMember record);
    
    
    
    
    public KuMember selectBymobile(String  mobile);
    
    /**
	 * 按条件查询记录
	 * 
	 * @param param
	 *            查询条件参数，包括WHERE条件、分页条件、排序条件
	 * @return 符合条件记录的实体对象的List
	 */

	public List<KuMember> selectPaging(Map param); 
	
	
	
	/**
	 * 按条件查询记录总的记录
	 * 
	 * @param param
	 *    查询条件参数，包括WHERE条件、
	 */

	public int selectCount(Map param); 
	
	public int updatePasswordByMobile(Map param);
}