package com.kuheng.dao;

import java.util.List;
import java.util.Map;

import com.kuheng.entity.member.KuBank;
import com.kuheng.entity.member.KuMobile;

public interface KuMobileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_mobile
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer itemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_mobile
     *
     * @mbggenerated
     */
    int insert(KuMobile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_mobile
     *
     * @mbggenerated
     */
    int insertSelective(KuMobile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_mobile
     *
     * @mbggenerated
     */
    KuMobile selectByPrimaryKey(Integer itemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_mobile
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(KuMobile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_mobile
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(KuMobile record);
    
    
    
    /**
   	 * 按条件查询记录
   	 * 
   	 * @param param
   	 *            查询条件参数，包括WHERE条件、分页条件、排序条件
   	 * @return 符合条件记录的实体对象的List
   	 */

   	public List<KuMobile> selectPaging(Map param); 
   	
   	
   	
   	/**
   	 * 按条件查询记录总的记录
   	 * 
   	 * @param param
   	 *    查询条件参数，包括WHERE条件、
   	 */

   	public int selectCount(Map param); 
   	/**
   	 * 按条件查询记录
   	 * 
   	 * @param param
   	 *            查询条件参数，id
   	 * @return 符合条件记录的Map的List
   	 */
   	public List<Map<String,Object>> selectByUserId(Long userId); 
   	/**
   	 * 按条件查询记录
   	 * 
   	 * @param param
   	 *            查询条件参数，货主id
   	 * @return 符合条件记录的Map的List
   	 */
   	public List<KuMobile> selectByUserId2(Long userId2);
}