package com.kuheng.dao;

import java.util.List;
import java.util.Map;

import com.kuheng.entity.member.KuMember;
import com.kuheng.entity.member.KuOldCar;

public interface KuOldCarMapper {
	 /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_old_car
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    int deleteByPrimaryKey(Integer itemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_old_car
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    int insert(KuOldCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_old_car
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    int insertSelective(KuOldCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_old_car
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    KuOldCar selectByPrimaryKey(Integer itemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_old_car
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    int updateByPrimaryKeySelective(KuOldCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_old_car
     *
     * @mbggenerated Sun May 21 11:13:41 CST 2017
     */
    int updateByPrimaryKey(KuOldCar record);
    
    
    
    
    /**
	 * 按条件查询记录
	 * 
	 * @param param
	 *            查询条件参数，包括WHERE条件、分页条件、排序条件
	 * @return 符合条件记录的实体对象的List
	 */

	public List<KuOldCar> selectPaging(Map param); 
	
	
	
	/**
	 * 按条件查询记录总的记录
	 * 
	 * @param param
	 *    查询条件参数，包括WHERE条件、
	 */

	public int selectCount(Map param); 
	
	 /**
		 * 按条件查询记录
		 * 
		 * @param param
		 *            查询条件参数，包括省名　和　市名
		 * @return 符合条件记录的实体对象的List
		 */
	public List<Map<String, Object>> selectByMobileAddress(String province,String city); 
	/**
	 * 按条件查询记录
	 * 
	 * @param param
	 *            查询条件参数，城市id
	 * @return 符合条件记录的实体对象的List
	 */
//	public List<Map<String, Object>> selectByCityId(Integer cityId); 
	/**
	 * 按条件查询记录
	 * 
	 * @param param
	 *            查询条件参数，itemid
	 * @return 符合条件记录的实体对象的map
	 */
	public Map<String, Object> selectById(Integer itemid); 
	/**
	 * 按条件查询记录
	 * 
	 * @param param
	 *            查询条件参数，筛选条件的map集合
	 * @return 符合条件记录的实体对象的List
	 */
	public List<Map<String, Object>> selectBySearch(Map<String, Object> map);
	/**
	 * 按条件查询记录
	 * 
	 * @param param
	 *            查询条件参数，userid
	 * @return 符合条件记录的实体对象的List
	 */
	public List<Map<String, Object>> selectCarByUserId(Integer userId); 
}