package com.kuheng.dao;

import java.util.List;
import java.util.Map;

import com.kuheng.entity.member.KuOrdered;

public interface KuOrderedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_ordered
     *
     * @mbggenerated Sat Jul 15 09:11:17 CST 2017
     */
    int deleteByPrimaryKey(Integer itemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_ordered
     *
     * @mbggenerated Sat Jul 15 09:11:17 CST 2017
     */
    int insert(KuOrdered record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_ordered
     *
     * @mbggenerated Sat Jul 15 09:11:17 CST 2017
     */
    int insertSelective(KuOrdered record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_ordered
     *
     * @mbggenerated Sat Jul 15 09:11:17 CST 2017
     */
    KuOrdered selectByPrimaryKey(Integer itemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_ordered
     *
     * @mbggenerated Sat Jul 15 09:11:17 CST 2017
     */
    int updateByPrimaryKeySelective(KuOrdered record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_ordered
     *
     * @mbggenerated Sat Jul 15 09:11:17 CST 2017
     */
    int updateByPrimaryKey(KuOrdered record);
    
    
    
    /**
	 * 按条件查询记录
	 * 
	 * @param param
	 *            查询条件参数，包括WHERE条件、分页条件、排序条件
	 * @return 符合条件记录的实体对象的List
	 */

	public List<KuOrdered> selectPaging(Map param); 
	
	/**
	 * 按条件查询记录
	 * 
	 * @param param
	 *            查询条件参数，包括userId,state
	 * @return 符合条件记录的实体对象的List
	 */
	public List<Map<String,Object>> selectMyOrderByState(Map param);
	/**
	 * 按条件查询记录总的记录
	 * 
	 * @param param
	 *    查询条件参数，包括WHERE条件、
	 */

	public int selectCount(Map param); 
	 /**
		 * 按条件查询记录
		 * 
		 * @param param
		 *            查询条件参数，itemid
		 * @return 符合条件记录的Map
		 */
	public Map<String,Object> selectWayBillById(Integer itemId);
	
	
	int updateByOrderId(KuOrdered record);
	
	public List<KuOrdered> selectPagingByTime(Map param); 
	/**
	 * 
	 * @param param
	 * 			根据userid和ordersid查询时候有到期未付信息费的订单
	 * @return 
	 */
	int selectCountByOidAndUid(Map param);
	/**
	 * 
	 * @param param
	 * 			将到期未付费的订单状态改为3	
	 * @return
	 */
	int updateStateByOidAndUid(Map param);
}