package com.kuheng.dao;

import com.kuheng.entity.member.KuReceipt;

public interface KuReceiptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_receipt
     *
     * @mbg.generated Tue Dec 19 09:21:00 CST 2017
     */
    int deleteByPrimaryKey(Integer itemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_receipt
     *
     * @mbg.generated Tue Dec 19 09:21:00 CST 2017
     */
    int insert(KuReceipt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_receipt
     *
     * @mbg.generated Tue Dec 19 09:21:00 CST 2017
     */
    int insertSelective(KuReceipt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_receipt
     *
     * @mbg.generated Tue Dec 19 09:21:00 CST 2017
     */
    KuReceipt selectByPrimaryKey(Integer itemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_receipt
     *
     * @mbg.generated Tue Dec 19 09:21:00 CST 2017
     */
    int updateByPrimaryKeySelective(KuReceipt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_receipt
     *
     * @mbg.generated Tue Dec 19 09:21:00 CST 2017
     */
    int updateByPrimaryKey(KuReceipt record);
}