package com.kuheng.dao;

import com.kuheng.entity.member.KuSender;

public interface KuSenderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_sender
     *
     * @mbg.generated Fri Sep 08 09:44:08 CST 2017
     */
    int deleteByPrimaryKey(Long userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_sender
     *
     * @mbg.generated Fri Sep 08 09:44:08 CST 2017
     */
    int insert(KuSender record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_sender
     *
     * @mbg.generated Fri Sep 08 09:44:08 CST 2017
     */
    int insertSelective(KuSender record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_sender
     *
     * @mbg.generated Fri Sep 08 09:44:08 CST 2017
     */
    KuSender selectByPrimaryKey(Long userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_sender
     *
     * @mbg.generated Fri Sep 08 09:44:08 CST 2017
     */
    int updateByPrimaryKeySelective(KuSender record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ku_sender
     *
     * @mbg.generated Fri Sep 08 09:44:08 CST 2017
     */
    int updateByPrimaryKey(KuSender record);
}